use super::*;
fn base(n:&str)->PathBuf{let p=PathBuf::from(std::env::var_os("FK_G33_ROOT").unwrap()).join(n);fs::create_dir(&p).unwrap();p}
fn store(n:&str)->Store{Store::create(&base(n).join("store")).unwrap()}
fn staged(s:&Store,text:&str)->(PathBuf,Vec<u8>,String){let p=s.staging_directory().unwrap();fs::write(p.join("worker.txt"),text).unwrap();let bytes=serde_json::to_vec(&Manifest{schema:1,component:"python-tools".into(),files:vec![Entry{path:"worker.txt".into(),bytes:text.len()as u64,sha256:hash(text.as_bytes())}]}).unwrap();let pin=hash(&bytes);(p,bytes,pin)}
#[test]fn install_acquire_and_reopen(){let s=store("install");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();let a=Store::open(&s.root).unwrap().acquire(&m,&h).unwrap();assert_eq!(fs::read(a.path.join("worker.txt")).unwrap(),b"one");assert_eq!(a.generation,h);}
#[test]fn shared_readers_block_mutation_until_last_guard(){let s=store("busy");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();let a=s.acquire(&m,&h).unwrap();let b=s.acquire(&m,&h).unwrap();assert!(s.deactivate().unwrap_err().contains("busy"));drop(a);assert!(s.deactivate().is_err());drop(b);s.deactivate().unwrap();}
#[test]fn upgrade_rollback_and_logical_uninstall_preserve_bytes(){let s=store("upgrade");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();let(p2,m2,h2)=staged(&s,"two");s.install(&p2,&m2,&h2).unwrap();assert_eq!(s.selection().unwrap().previous,Some(h.clone()));s.rollback(&m,&h).unwrap();assert!(s.acquire(&m,&h).is_ok());s.deactivate().unwrap();assert!(s.acquire(&m,&h).is_err());assert!(s.root.join("generations").join(&h2).join("worker.txt").exists());s.rollback(&m,&h).unwrap();assert!(s.acquire(&m,&h).is_ok());}
#[test]fn corrupt_new_generation_never_changes_old_selection(){let s=store("bad-stage");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();let(before,_,_)=staged(&s,"two");let bytes=fs::read(s.root.join("selection.json")).unwrap();assert!(s.install(&before,&m,&h).is_err());assert_eq!(fs::read(s.root.join("selection.json")).unwrap(),bytes);assert!(before.exists());assert!(s.acquire(&m,&h).is_ok());}
#[test]fn added_and_missing_files_are_not_accepted(){for (n,extra)in[("extra",true),("missing",false)]{let s=store(n);let(p,m,h)=staged(&s,"one");if extra{fs::write(p.join("foreign.txt"),b"preserve").unwrap();}else{fs::remove_file(p.join("worker.txt")).unwrap();}assert!(s.install(&p,&m,&h).is_err());assert!(s.selection().unwrap().active.is_none());}}
#[test]fn bad_pin_does_not_move_stage(){let s=store("pin");let(p,m,_)=staged(&s,"one");assert!(s.install(&p,&m,&"0".repeat(64)).is_err());assert!(p.exists());}
#[test]fn tampered_active_is_not_executable_and_previous_can_recover(){let s=store("tamper");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();let(p2,m2,h2)=staged(&s,"two");s.install(&p2,&m2,&h2).unwrap();fs::write(s.root.join("generations").join(&h2).join("worker.txt"),b"bad").unwrap();assert!(s.acquire(&m2,&h2).is_err());s.rollback(&m,&h).unwrap();assert!(s.acquire(&m,&h).is_ok());}
#[test]fn selection_corruption_is_not_auto_repaired(){let s=store("bad-selection");fs::write(s.root.join("selection.json"),b"{partial").unwrap();assert!(s.selection().is_err());assert!(s.deactivate().is_err());assert_eq!(fs::read(s.root.join("selection.json")).unwrap(),b"{partial");}
#[test]fn manifest_paths_and_collisions_rejected(){for name in ["../x","/absolute","C:/x","a\\b","CON.txt","a.","a ","a//b"]{let m=serde_json::to_vec(&Manifest{schema:1,component:"python-tools".into(),files:vec![Entry{path:name.into(),bytes:0,sha256:hash(b"")}]}).unwrap();assert!(approved(&m,&hash(&m)).is_err(),"{name}");}for names in [["a","A"],["a","a/b"]]{let m=serde_json::to_vec(&Manifest{schema:1,component:"python-tools".into(),files:names.into_iter().map(|n|Entry{path:n.into(),bytes:0,sha256:hash(b"")}).collect()}).unwrap();assert!(approved(&m,&hash(&m)).is_err());}}
#[test]fn create_refuses_existing_foreign_directory(){let p=base("foreign");fs::write(p.join("keep"),b"user fixture").unwrap();assert!(Store::create(&p).is_err());assert!(Store::open(&p).is_err());assert_eq!(fs::read(p.join("keep")).unwrap(),b"user fixture");}
#[test]fn unavailable_generation_and_duplicate_publish_preserve_selection(){let s=store("duplicate");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();let(p2,m2,h2)=staged(&s,"one");assert!(s.install(&p2,&m2,&h2).is_err());assert!(s.rollback(&m,&"0".repeat(64)).is_err());assert_eq!(s.selection().unwrap().active,Some(h));}
#[test]
#[ignore = "Explicit isolated helper or real-package fixture only"]
fn subprocess_crash_helper(){if let Some(p)=std::env::var_os("FK_G33_CRASH_STORE"){let s=Store::open(Path::new(&p)).unwrap();let(stage,m,h)=staged(&s,"new-crash-generation");s.install_inner(&stage,&m,&h,||std::process::exit(77)).unwrap();panic!("did not crash");}}
#[test]fn process_exit_between_rename_and_publish_keeps_old_active(){let s=store("crash");let(p,m,h)=staged(&s,"old");s.install(&p,&m,&h).unwrap();let status=std::process::Command::new(std::env::current_exe().unwrap()).args(["--ignored","--exact","component_store::tests::subprocess_crash_helper","--nocapture"]).env("FK_G33_CRASH_STORE",&s.root).status().unwrap();assert_eq!(status.code(),Some(77));let reopened=Store::open(&s.root).unwrap();assert_eq!(reopened.selection().unwrap().active,Some(h.clone()));assert!(reopened.acquire(&m,&h).is_ok());assert_eq!(fs::read_dir(s.root.join("generations")).unwrap().count(),2);reopened.deactivate().unwrap();}
#[test]
#[ignore = "Explicit isolated helper or real-package fixture only"]
fn actual_component_relocation_store(){let Some(input)=std::env::var_os("FK_G33_REAL")else{return;};let s=Store::open(Path::new(&input)).unwrap();let stage=PathBuf::from(std::env::var_os("FK_G33_REAL_STAGE").unwrap());let bytes=fs::read(std::env::var_os("FK_G33_REAL_MANIFEST").unwrap()).unwrap();let pin=std::env::var("FK_G33_REAL_PIN").unwrap();s.install(&stage,&bytes,&pin).unwrap();let a=s.acquire(&bytes,&pin).unwrap();assert!(a.path.join("services/worker/.venv/Scripts/python.exe").is_file());assert!(s.deactivate().is_err());drop(a);s.deactivate().unwrap();s.rollback(&bytes,&pin).unwrap();assert!(s.acquire(&bytes,&pin).is_ok());}
#[test]
#[ignore = "Explicit isolated helper or real-package fixture only"]
fn prepare_real_store(){let Some(path)=std::env::var_os("FK_G33_PREPARE")else{return;};let s=Store::create(Path::new(&path)).unwrap();let stage=s.staging_directory().unwrap();println!("G33_STAGE={}",stage.display());}

#[test]fn junction_directories_are_rejected_without_touching_target(){
 use std::os::windows::process::CommandExt;
 for name in ["staging","generations"]{let s=store(&format!("junction-{name}"));let target=s.root.parent().unwrap().join("foreign-fixture");fs::create_dir(&target).unwrap();fs::write(target.join("keep"),b"keep").unwrap();let(stage,m,h)=staged(&s,"one");fs::rename(s.root.join(name),s.root.parent().unwrap().join(format!("retained-{name}"))).unwrap();let status=std::process::Command::new(std::env::var_os("FK_G33_PYTHON").unwrap()).arg("-B").arg(std::env::var_os("FK_G33_JUNCTION_HELPER").unwrap()).arg(s.root.join(name).to_string_lossy().trim_start_matches(r"\\?\")).arg(target.to_string_lossy().trim_start_matches(r"\\?\")).creation_flags(0x08000000).output().unwrap();assert!(status.status.success(),"junction fixture creation: {:?}; root={:?}; target={:?}",status,s.root,target);if name=="staging"{assert!(s.staging_directory().is_err());}else{assert!(s.install(&stage,&m,&h).is_err());}assert_eq!(fs::read(target.join("keep")).unwrap(),b"keep");assert!(s.selection().unwrap().active.is_none());}
}
#[test]fn corrupted_previous_is_never_selected(){let s=store("bad-previous");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();let(p2,m2,h2)=staged(&s,"two");s.install(&p2,&m2,&h2).unwrap();fs::write(s.root.join("generations").join(&h).join("worker.txt"),b"bad").unwrap();assert!(s.rollback(&m,&h).is_err());assert!(s.acquire(&m2,&h2).is_ok());}
#[test]fn incomplete_publication_files_are_never_promoted(){let s=store("unpublished");let(p,m,h)=staged(&s,"one");s.install(&p,&m,&h).unwrap();fs::write(s.root.join("selection-foreign.pending"),b"{partial").unwrap();assert_eq!(s.selection().unwrap().active,Some(h.clone()));assert!(s.acquire(&m,&h).is_ok());assert_eq!(fs::read(s.root.join("selection-foreign.pending")).unwrap(),b"{partial");}
#[test]fn manifest_limits_and_unknown_fields_fail_closed(){let m=serde_json::to_vec(&Manifest{schema:1,component:"python-tools".into(),files:vec![Entry{path:"worker.txt".into(),bytes:LIMIT+1,sha256:hash(b"")}]}).unwrap();assert!(approved(&m,&hash(&m)).is_err());let bad=br#"{"schema":1,"component":"python-tools","files":[],"allowUnverified":true}"#;assert!(approved(bad,&hash(bad)).is_err());}
