use super::*;
fn root()->PathBuf{PathBuf::from(std::env::var_os("FK_G36_ROOT").unwrap())}
fn setup(name:&str)->(Store,PathBuf,Vec<u8>,String,String){let base=root().join(name);fs::create_dir(&base).unwrap();let store=Store::create(&base.join("store")).unwrap();let input=PathBuf::from(std::env::var_os("FK_G36_INPUTS").unwrap()).join(name);let m=fs::read(input.join("manifest.json")).unwrap();let p=fs::read_to_string(input.join("pins.json")).unwrap();let p:serde_json::Value=serde_json::from_str(&p).unwrap();(store,input.join("archive.zip"),m,p["archive"].as_str().unwrap().into(),p["tree"].as_str().unwrap().into())}
fn install(s:&Store,a:&Path,m:&[u8],h:&str,p:&str)->Result<PathBuf,String>{install_policy(s,a,m,h,p,&AtomicBool::new(false),||{})}
fn stages(name:&str)->usize{fs::read_dir(root().join(name).join("store/staging")).unwrap().filter(|e|e.as_ref().unwrap().file_type().unwrap().is_dir()).count()}
#[test]fn g36_success_registers_approval_and_never_overwrites(){let(s,a,m,h,p)=setup("good");let path=install(&s,&a,&m,&h,&p).unwrap();assert!(path.is_dir());assert_eq!(s.selection().unwrap().active,Some(p.clone()));assert_eq!(fs::read(root().join("good/store/approved-tree.json")).unwrap(),m);let active=s.acquire(&m,&p).unwrap();assert!(s.deactivate().is_err());drop(active);assert!(install(&s,&a,&m,&h,&p).is_err());assert_eq!(stages("good"),0);assert_eq!(s.selection().unwrap().active,Some(p));}
#[test]fn g36_default_policy_rejects_custom_package(){let(s,a,m,_,_)=setup("default-policy");assert!(install_experimental(&s,&a,&m,&AtomicBool::new(false)).is_err());assert_eq!(stages("default-policy"),0);assert!(s.selection().unwrap().active.is_none());}
#[test]fn g36_wrong_archive_digest_does_not_stage(){let(s,a,m,_,p)=setup("wrong-hash");assert!(install(&s,&a,&m,&"0".repeat(64),&p).unwrap_err().contains("not approved"));assert_eq!(stages("wrong-hash"),0);}
#[test]fn g36_precancel_does_not_stage(){let(s,a,m,h,p)=setup("precancel");assert!(install_policy(&s,&a,&m,&h,&p,&AtomicBool::new(true),||{}).unwrap_err().contains("cancelled"));assert_eq!(stages("precancel"),0);}
#[test]fn g36_cancel_after_extraction_does_not_publish(){let(s,a,m,h,p)=setup("late-cancel");let cancel=AtomicBool::new(false);assert!(install_policy(&s,&a,&m,&h,&p,&cancel,||cancel.store(true,Ordering::Release)).unwrap_err().contains("cancelled"));assert!(s.selection().unwrap().active.is_none());assert_eq!(stages("late-cancel"),1);assert!(!root().join("late-cancel/store/approved-tree.json").exists());}
#[test]fn g36_unexpected_missing_duplicate_traversal_and_symlink_entries_never_extract(){for name in ["extra","missing","duplicate","traversal","symlink","bad-size"]{let(s,a,m,h,p)=setup(name);assert!(install(&s,&a,&m,&h,&p).is_err(),"{name}");assert!(s.selection().unwrap().active.is_none());let dirs:Vec<_>=fs::read_dir(root().join(name).join("store/staging")).unwrap().map(|e|e.unwrap().path()).filter(|p|p.is_dir()).collect();assert_eq!(dirs.len(),1,"{name}");assert_eq!(fs::read_dir(&dirs[0]).unwrap().count(),0,"{name}");assert!(!root().join(name).join("escape").exists());}}
#[test]fn g36_unsafe_manifest_is_rejected_before_stage(){let(s,a,m,h,p)=setup("unsafe-manifest");assert!(install(&s,&a,&m,&h,&p).is_err());assert_eq!(stages("unsafe-manifest"),0);}
#[test]fn g36_content_mismatch_keeps_old_selection_and_bytes(){let(s,a,m,h,p)=setup("bad-content");let stage=s.staging_directory().unwrap();fs::write(stage.join("old"),b"old").unwrap();let old=serde_json::to_vec(&serde_json::json!({"schema":1,"component":"python-tools","files":[{"path":"old","bytes":3,"sha256":format!("{:x}",Sha256::digest(b"old"))}]})).unwrap();let oldpin=format!("{:x}",Sha256::digest(&old));s.install(&stage,&old,&oldpin).unwrap();assert!(install(&s,&a,&m,&h,&p).is_err());assert_eq!(s.selection().unwrap().active,Some(oldpin.clone()));assert!(s.acquire(&old,&oldpin).is_ok());assert!(!root().join("bad-content/store/approved-tree.json").exists());}
#[test]fn g36_exclusive_transaction_blocks_readers_and_mutators(){let(s,_,m,_,p)=setup("transaction");let transaction=s.begin_import(&m,&p).unwrap();let stage=transaction.stage().to_owned();assert!(s.selection().is_err());assert!(s.deactivate().is_err());assert!(s.begin_import(&m,&p).is_err());drop(transaction);assert!(stage.is_dir());assert!(s.selection().unwrap().active.is_none());}
#[test]fn g36_conflicting_approval_is_never_overwritten(){let(s,a,m,h,p)=setup("approval-conflict");let file=root().join("approval-conflict/store/approved-tree.json");fs::write(&file,b"preserved unknown approval").unwrap();assert!(install(&s,&a,&m,&h,&p).is_err());assert_eq!(fs::read(file).unwrap(),b"preserved unknown approval");assert!(s.selection().unwrap().active.is_none());}
#[test]#[ignore="Fresh real archive import using inbox tar, no Python worker"]fn g36_real(){let base=root().join("real");fs::create_dir(&base).unwrap();let store=Store::create(&base.join("store")).unwrap();let manifest=fs::read(std::env::var_os("FK_G36_REAL_MANIFEST").unwrap()).unwrap();let archive=PathBuf::from(std::env::var_os("FK_G36_REAL_ARCHIVE").unwrap());let generation=install_experimental(&store,&archive,&manifest,&AtomicBool::new(false)).unwrap();let active=store.acquire(&manifest,TREE_PIN).unwrap();assert_eq!(active.path,generation);assert!(store.deactivate().is_err());drop(active);assert_eq!(fs::read(base.join("store/approved-tree.json")).unwrap(),manifest);store.deactivate().unwrap();store.rollback(&manifest,TREE_PIN).unwrap();drop(store.acquire(&manifest,TREE_PIN).unwrap());store.deactivate().unwrap();println!("G36_REAL_NATIVE_IMPORT_PASS");}
#[test]#[ignore="Fresh real extraction cancellation; never reuses an import fixture"]fn g36_real_cancel(){let base=root().join("real-cancel");fs::create_dir(&base).unwrap();let store=Store::create(&base.join("store")).unwrap();let manifest=fs::read(std::env::var_os("FK_G36_REAL_MANIFEST").unwrap()).unwrap();let archive=PathBuf::from(std::env::var_os("FK_G36_REAL_ARCHIVE").unwrap());let cancel=AtomicBool::new(false);std::thread::scope(|scope|{let thread=scope.spawn(||{let deadline=Instant::now()+Duration::from_secs(100);loop{for item in fs::read_dir(base.join("store/staging")).unwrap(){let p=item.unwrap().path();if p.is_dir()&&p.join("worker-component.json").exists(){cancel.store(true,Ordering::Release);return;}}assert!(Instant::now()<deadline,"extraction never began");std::thread::sleep(Duration::from_millis(2));}});let result=install_experimental(&store,&archive,&manifest,&cancel);thread.join().unwrap();assert!(result.unwrap_err().contains("cancelled"));});assert!(store.selection().unwrap().active.is_none());assert!(!base.join("store/approved-tree.json").exists());assert_eq!(fs::read_dir(base.join("store/generations")).unwrap().count(),0);println!("G36_REAL_NATIVE_CANCEL_PASS");}
#[test]fn g36_entry_budget_rejected_before_staging(){let(s,a,m,h,p)=setup("oversize-entry");assert!(install(&s,&a,&m,&h,&p).unwrap_err().contains("budget"));assert_eq!(stages("oversize-entry"),0);}
#[test]fn g37_space_boundary_and_overflow_fail_closed(){let payload=521616107;let need=required_space(payload).unwrap();assert!(check_space(payload,need).is_ok());assert!(check_space(payload,need-1).unwrap_err().contains("Insufficient free space"));assert!(check_space(u64::MAX,u64::MAX).is_err());}
#[test]fn g37_space_query_rejects_missing_and_non_directory_paths(){let base=root().join("space-query");fs::create_dir(&base).unwrap();assert!(available_space(&base).is_ok());assert!(available_space(&base.join("missing")).is_err());fs::write(base.join("file"),b"preserve").unwrap();assert!(available_space(&base.join("file")).is_err());assert_eq!(fs::read(base.join("file")).unwrap(),b"preserve");}
#[test]fn g37_verified_disk_handle_rewinds_and_supports_unicode_archive_path(){
 let(s,a,m,h,p)=setup("handle");let renamed=a.with_file_name("已校验-🦋.zip");fs::rename(&a,&renamed).unwrap();let cancel=AtomicBool::new(false);let file=archive(&renamed,&h,&cancel).unwrap();let transaction=Arc::new(s.begin_import(&m,&p).unwrap());let tool=inbox_tar().unwrap();
 let mut borrowed=file.as_ref();borrowed.seek(SeekFrom::End(0)).unwrap();
 let names=run_tar(&tool,&transaction,&file,"names",&cancel).unwrap();let types=run_tar(&tool,&transaction,&file,"types",&cancel).unwrap();listing(&names,&types,&transaction).unwrap();
 run_tar(&tool,&transaction,&file,"extract",&cancel).unwrap();let transaction=Arc::try_unwrap(transaction).ok().unwrap();let path=transaction.commit(&cancel).unwrap();assert_eq!(fs::read(path.join("services/worker/entry.txt")).unwrap(),b"expected");drop(s.acquire(&m,&p).unwrap());
}
