use super::*;
fn root()->PathBuf{PathBuf::from(std::env::var_os("FK_G41_ROOT").unwrap())}
fn work(name:&str)->Arc<Work>{let p=root().join(name);fs::create_dir(&p).unwrap();Work::create(&p,1024*1024).unwrap()}
fn url(path:&str)->String{format!("{}/{}",std::env::var("FK_G41_SERVER").unwrap(),path)}
fn pin(bytes:&[u8])->String{format!("{:x}",Sha256::digest(bytes))}
#[test]fn production_rejects_http_file_credentials_and_bad_urls(){for s in ["http://127.0.0.1:9/a","file:///a","https://user@host/a","https://host/a#fragment","https://host/a\n--insecure","https://host/","https://host\\evil/a"]{assert!(validate_url(s,Protocol::Https).is_err(),"{s}");}assert!(validate_url("https://downloads.example.org/fixed.zip",Protocol::Https).is_ok());}
#[test]fn test_protocol_cannot_escape_loopback_authority(){for s in ["http://localhost:9/a","http://127.0.0.1.evil:9/a","http://192.168.1.1:9/a","http://127.0.0.1:0/a"]{assert!(validate_url(s,Protocol::Loopback).is_err());}}
#[test]fn empty_sources_do_not_create_cache(){let p=root().join("empty");fs::create_dir(&p).unwrap();assert!(install_from_https(&p,&[],&[],&AtomicBool::new(false)).is_err());assert_eq!(fs::read_dir(p).unwrap().count(),0);}
#[test]fn real_http_body_is_verified_not_just_status(){let w=work("body");let p=fetch(&w,&[url("good")],8,&pin(b"expected"),Protocol::Loopback,"ok",&AtomicBool::new(false)).unwrap();assert_eq!(fs::read(p).unwrap(),b"expected");}
#[test]fn wrong_hash_is_not_a_success(){let w=work("hash");assert!(fetch(&w,&[url("bad")],8,&pin(b"expected"),Protocol::Loopback,"bad",&AtomicBool::new(false)).unwrap_err().contains("SHA-256"));assert!(w.path.join("bad-0.part").exists());}
#[test]fn disconnected_or_short_body_is_not_success(){for endpoint in ["short","disconnect"]{let w=work(endpoint);assert!(fetch(&w,&[url(endpoint)],8,&pin(b"expected"),Protocol::Loopback,"body",&AtomicBool::new(false)).is_err());}}
#[test]fn missing_primary_tries_verified_backup_and_retains_failure(){let w=work("fallback");let p=fetch(&w,&[url("missing"),url("good")],8,&pin(b"expected"),Protocol::Loopback,"body",&AtomicBool::new(false)).unwrap();assert_eq!(fs::read(p).unwrap(),b"expected");assert!(w.path.join("body-0.stderr").exists());}
#[test]fn redirects_do_not_escape_loopback_test(){let w=work("redirect");assert!(fetch(&w,&[url("redirect")],8,&pin(b"expected"),Protocol::Loopback,"body",&AtomicBool::new(false)).is_err());}
#[test]fn oversize_server_body_is_rejected(){let w=work("oversize");assert!(fetch(&w,&[url("oversize")],8,&pin(b"expected"),Protocol::Loopback,"body",&AtomicBool::new(false)).is_err());}
#[test]fn precancel_writes_no_attempt(){let w=work("precancel");assert!(fetch(&w,&[url("good")],8,&pin(b"expected"),Protocol::Loopback,"body",&AtomicBool::new(true)).is_err());assert!(!w.path.join("body-0.part").exists());}
#[test]fn cancellation_during_network_transfer_keeps_partial_and_releases_work(){let w=work("cancel");let cancel=AtomicBool::new(false);std::thread::scope(|s|{let watched=w.path.clone();let token=&cancel;s.spawn(move||{let deadline=Instant::now()+Duration::from_secs(15);loop{if fs::metadata(watched.join("body-0.part")).map(|m|m.len()>0).unwrap_or(false){token.store(true,Ordering::Release);break;}assert!(Instant::now()<deadline);std::thread::sleep(Duration::from_millis(2));}});assert!(fetch(&w,&[url("slow"),url("good")],65536,&pin(&vec![b'x';65536]),Protocol::Loopback,"body",&cancel).is_err());});assert!(!w.path.join("body-1.part").exists());assert_eq!(Arc::strong_count(&w),1);assert!(fs::metadata(w.path.join("body-0.part")).unwrap().len()>0);}
#[test]#[ignore="Real audited package over private loopback server, then native installation"]fn real_network_import(){let components=root().join("real-network");fs::create_dir(&components).unwrap();let result=install(&components,&[url("manifest")],&[url("missing"),url("archive")],Protocol::Loopback,&AtomicBool::new(false)).unwrap();let store=Store::open(&components.join("python-tools-v2")).unwrap();let manifest=fs::read(std::env::var_os("FK_G41_MANIFEST").unwrap()).unwrap();let active=store.acquire(&manifest,MANIFEST_SHA).unwrap();assert_eq!(active.path,result);drop(active);store.deactivate().unwrap();println!("G41_REAL_HTTP_DOWNLOAD_HASH_IMPORT_PASS");}
#[test]#[ignore="Real public HTTPS transport of pinned legal source only; not a worker release"]fn live_https_corresponding_source(){let w=work("live-https");let p=fetch(&w,&["https://static.crates.io/crates/rav1d/rav1d-1.1.0.crate".into()],1453317,"1932f060d5e7bd49dc9f8b272c1dc5e9ce0ffe141c28be900265d3989b36c9ed",Protocol::Https,"legal-source",&AtomicBool::new(false)).unwrap();assert_eq!(fs::metadata(p).unwrap().len(),1453317);println!("G41_PUBLIC_HTTPS_PINNED_LEGAL_SOURCE_PASS");}
