use super::*;
use std::time::{Duration,Instant};
fn fresh()->Arc<Controller>{Arc::new(Controller::default())}
fn sources()->Option<crate::worker_component_source::Sources>{Some(crate::worker_component_source::test_sources())}
fn unused(_: &Arc<Controller>,_:PathBuf,_:crate::worker_component_source::Sources)->Result<Status,String>{panic!("must not start a transfer")}
#[test]fn get_is_read_only_even_with_download_payload_and_root_error(){let c=fresh();let v=dispatch_download_using(&c,"GET",&serde_json::json!({"action":"download","acknowledged":true}),true,Err("unused root".into()),sources(),unused).unwrap();assert_eq!(v["operation"]["phase"],"idle");}
#[test]fn no_source_no_confirmation_and_disabled_gate_never_admit(){for(enabled,src,args)in [(false,sources(),serde_json::json!({"action":"download","acknowledged":true})),(true,None,serde_json::json!({"action":"download","acknowledged":true})),(true,sources(),serde_json::json!({"action":"download","acknowledged":false}))]{let c=fresh();assert!(dispatch_download_using(&c,"POST",&args,enabled,Err("unused".into()),src,unused).is_err());assert_eq!(c.status().unwrap().phase,"idle");}}
#[test]fn request_rejects_url_hash_destination_and_unknown_actions(){for args in [serde_json::json!({"action":"download","acknowledged":true,"url":"https://bad/a"}),serde_json::json!({"action":"download","acknowledged":true,"sha256":"bad"}),serde_json::json!({"action":"download","acknowledged":true,"destination":"E:/bad"}),serde_json::json!({"action":"download","acknowledged":"true"}),serde_json::json!({"action":"update"})]{let c=fresh();assert!(dispatch_download_using(&c,"POST",&args,true,Err("unused".into()),sources(),unused).is_err());assert_eq!(c.status().unwrap().phase,"idle");}}
#[test]fn download_and_local_import_share_one_admission(){let c=fresh();c.reserve().unwrap();assert!(dispatch_download_using(&c,"POST",&serde_json::json!({"action":"download","acknowledged":true}),true,Ok(PathBuf::from("E:/unused-fixture")),sources(),|c,p,s|c.start_download(p,s)).is_err());assert_eq!(c.status().unwrap().kind,"local-import");}
#[test]fn cancel_needs_current_id_but_no_source_or_root(){let c=fresh();let(id,_)=c.reserve_kind("download").unwrap();let v=dispatch_download_using(&c,"POST",&serde_json::json!({"action":"cancel","id":id}),true,Err("unused".into()),None,unused).unwrap();assert_eq!(v["operation"]["phase"],"cancelling");assert_eq!(v["operation"]["kind"],"download");assert!(dispatch_download_using(&c,"POST",&serde_json::json!({"action":"cancel","id":"old"}),true,Err("unused".into()),None,unused).is_err());}
#[test]fn stage_callbacks_do_not_undo_cancel_or_terminal_state(){let c=fresh();let(id,_)=c.reserve_kind("download").unwrap();c.update_stage("stale","manifest");assert_eq!(c.status().unwrap().stage,"queued");c.cancel(&id).unwrap();c.update_stage(&id,"archive");assert_eq!(c.status().unwrap().phase,"cancelling");assert_eq!(c.status().unwrap().stage,"archive");c.finish(&id,Ok(()));c.update_stage(&id,"install");assert_eq!(c.status().unwrap().stage,"done");assert_eq!(c.status().unwrap().phase,"succeeded");}
#[test]fn failed_task_can_be_explicitly_retried_with_new_id(){let c=fresh();let(old,_)=c.reserve_kind("download").unwrap();c.finish(&old,Err("offline".into()));let(new,_)=c.reserve_kind("download").unwrap();assert_ne!(old,new);assert_eq!(c.status().unwrap().stage,"queued");assert!(c.status().unwrap().error.is_none());}
#[test]#[ignore="Actual request/controller/HTTP import in fresh isolated root; not desktop IPC"]fn real_download_request_controller(){
 let root=PathBuf::from(std::env::var_os("FK_G42_ROOT").unwrap()).join("request-real");std::fs::create_dir(&root).unwrap();let origin=std::env::var("FK_G41_SERVER").unwrap();let c=fresh();let stages=Arc::new(Mutex::new(Vec::<String>::new()));let trace=stages.clone();
 let accepted=dispatch_download_using(&c,"POST",&serde_json::json!({"action":"download","acknowledged":true}),true,Ok(root.clone()),sources(),move|c,root,_|c.launch_kind("download",move|cancel,report|crate::worker_download::test_install_loopback_progress(&root,&origin,cancel,&|stage|{report(stage);trace.lock().unwrap().push(stage.into());}).map(|_|()))).unwrap();
 assert_eq!(accepted["operation"]["kind"],"download");let deadline=Instant::now()+Duration::from_secs(240);
 loop{let status=c.status().unwrap();if !matches!(status.phase.as_str(),"running"|"cancelling"){assert_eq!(status.phase,"succeeded","{status:?}");assert_eq!(status.stage,"done");break;}assert!(Instant::now()<deadline);std::thread::sleep(Duration::from_millis(10));}
 assert_eq!(*stages.lock().unwrap(),vec!["manifest","archive","install"]);let store=crate::component_store::Store::open(&root.join("python-tools-v2")).unwrap();let manifest=std::fs::read(std::env::var_os("FK_G41_MANIFEST").unwrap()).unwrap();drop(store.acquire(&manifest,PIN).unwrap());store.deactivate().unwrap();println!("G42_REQUEST_CONTROLLER_NETWORK_IMPORT_PASS");
}
#[test]#[ignore="Actual cancellation via shared request/controller during private HTTP transfer"]fn real_download_request_cancel(){
 let root=PathBuf::from(std::env::var_os("FK_G42_ROOT").unwrap()).join("request-cancel");std::fs::create_dir(&root).unwrap();let origin=std::env::var("FK_G42_SLOW_SERVER").unwrap();let c=fresh();
 let accepted=dispatch_download_using(&c,"POST",&serde_json::json!({"action":"download","acknowledged":true}),true,Ok(root.clone()),sources(),move|c,root,_|c.launch_kind("download",move|cancel,report|crate::worker_download::test_install_loopback_progress(&root,&origin,cancel,report).map(|_|()))).unwrap();
 let id=accepted["operation"]["id"].as_str().unwrap();let deadline=Instant::now()+Duration::from_secs(60);loop{let found=std::fs::read_dir(&root).unwrap().filter_map(Result::ok).any(|e|std::fs::metadata(e.path().join("archive-1.part")).map(|m|m.len()>0).unwrap_or(false));if found{break;}assert_eq!(c.status().unwrap().phase,"running");assert!(Instant::now()<deadline);std::thread::sleep(Duration::from_millis(5));}
 let requested=dispatch_download_using(&c,"POST",&serde_json::json!({"action":"cancel","id":id}),true,Err("unused".into()),None,unused).unwrap();assert_eq!(requested["operation"]["phase"],"cancelling");
 loop{let status=c.status().unwrap();if status.phase=="failed"{assert!(status.error.unwrap().contains("cancelled"));break;}assert!(Instant::now()<deadline);std::thread::sleep(Duration::from_millis(5));}
 assert!(!root.join("python-tools-v2").exists());println!("G42_REQUEST_CONTROLLER_NETWORK_CANCEL_PASS");
}
