use super::*;
use std::time::{Duration,Instant};
fn controller_new()->Arc<Controller>{Arc::new(Controller::default())}
fn wait(c:&Controller)->Status{let deadline=Instant::now()+Duration::from_secs(240);loop{let s=c.status().unwrap();if !matches!(s.phase.as_str(),"running"|"cancelling"){return s;}assert!(Instant::now()<deadline,"controller did not complete");std::thread::sleep(Duration::from_millis(5));}}
#[test]fn idle_does_not_claim_installed(){let s=controller_new().status().unwrap();assert_eq!(s.phase,"idle");assert!(s.id.is_none());}
#[test]fn duplicate_admission_and_stale_cancel_rejected(){let c=controller_new();let(id,token)=c.reserve().unwrap();assert!(c.reserve().is_err());assert!(c.cancel("wrong").is_err());assert!(!token.load(Ordering::Acquire));assert_eq!(c.cancel(&id).unwrap().phase,"cancelling");assert!(token.load(Ordering::Acquire));assert!(c.reserve().is_err());}
#[test]fn cancellation_request_is_not_terminal_or_success(){let c=controller_new();let(id,_)=c.reserve().unwrap();c.cancel(&id).unwrap();assert_eq!(c.status().unwrap().phase,"cancelling");c.finish(&id,Err("cancelled before commit".into()));assert_eq!(c.status().unwrap().phase,"failed");}
#[test]fn late_cancellation_does_not_relabel_committed_success(){let c=controller_new();let(id,_)=c.reserve().unwrap();c.cancel(&id).unwrap();c.finish(&id,Ok(()));let s=c.cancel(&id).unwrap();assert_eq!(s.phase,"succeeded");assert!(s.cancel_requested);}
#[test]fn stale_completion_cannot_replace_new_operation(){let c=controller_new();let(old,_)=c.reserve().unwrap();c.finish(&old,Ok(()));let(new,_)=c.reserve().unwrap();c.finish(&old,Err("stale".into()));assert_eq!(c.status().unwrap().id,Some(new));assert_eq!(c.status().unwrap().phase,"running");}
#[test]fn async_result_and_panic_are_observable(){let c=controller_new();let s=c.launch(|_|Ok(())).unwrap();assert!(s.id.is_some());assert_eq!(wait(&c).phase,"succeeded");c.launch(|_|panic!("intentional test panic")).unwrap();assert_eq!(wait(&c).phase,"failed");}
#[test]fn async_cancellation_holds_admission_until_work_returns(){let c=controller_new();let s=c.launch(|cancel|{while !cancel.load(Ordering::Acquire){std::thread::yield_now();}Err("cancelled".into())}).unwrap();c.cancel(s.id.as_ref().unwrap()).unwrap();assert_eq!(wait(&c).phase,"failed");}
#[test]fn relative_inputs_rejected_before_admission(){let c=controller_new();assert!(c.start("relative".into(),"archive".into(),"manifest".into()).is_err());assert_eq!(c.status().unwrap().phase,"idle");}
#[test]fn unapproved_manifest_cannot_create_store(){let base=PathBuf::from(std::env::var_os("FK_G38_ROOT").unwrap()).join("unapproved");std::fs::create_dir(&base).unwrap();let manifest=base.join("manifest.json");std::fs::write(&manifest,b"{}").unwrap();let c=controller_new();c.start(base.clone(),base.join("absent.zip"),manifest).unwrap();assert_eq!(wait(&c).phase,"failed");assert!(!base.join("python-tools-v2").exists());}
#[test]#[ignore="Fresh real package through asynchronous control, no UI or worker"]fn real_controller_import(){
 let base=PathBuf::from(std::env::var_os("FK_G38_ROOT").unwrap()).join("real-control");std::fs::create_dir(&base).unwrap();let manifest=PathBuf::from(std::env::var_os("FK_G36_REAL_MANIFEST").unwrap());let archive=PathBuf::from(std::env::var_os("FK_G36_REAL_ARCHIVE").unwrap());
 let c=controller_new();let accepted=c.start(base.clone(),archive,manifest.clone()).unwrap();assert!(accepted.id.is_some());assert!(c.reserve().is_err());let result=wait(&c);assert_eq!(result.phase,"succeeded","{result:?}");let store=crate::component_store::Store::open(&base.join("python-tools-v2")).unwrap();let bytes=std::fs::read(manifest).unwrap();let active=store.acquire(&bytes,PIN).unwrap();assert!(store.deactivate().is_err());drop(active);store.deactivate().unwrap();println!("G38_REAL_CONTROL_IMPORT_PASS");
}
#[test]#[ignore="Fresh actual extraction cancellation through controller"]fn real_controller_cancel(){
 let base=PathBuf::from(std::env::var_os("FK_G38_ROOT").unwrap()).join("real-control-cancel");std::fs::create_dir(&base).unwrap();let c=controller_new();let s=c.start(base.clone(),PathBuf::from(std::env::var_os("FK_G36_REAL_ARCHIVE").unwrap()),PathBuf::from(std::env::var_os("FK_G36_REAL_MANIFEST").unwrap())).unwrap();
 let deadline=Instant::now()+Duration::from_secs(100);loop{let stage=base.join("python-tools-v2/staging");if let Ok(dirs)=std::fs::read_dir(stage){if dirs.filter_map(Result::ok).any(|e|e.path().is_dir()&&e.path().join("worker-component.json").exists()){break;}}assert!(matches!(c.status().unwrap().phase.as_str(),"running"|"cancelling"));assert!(Instant::now()<deadline);std::thread::sleep(Duration::from_millis(2));}
 let requested=c.cancel(s.id.as_ref().unwrap()).unwrap();assert!(requested.cancel_requested);let result=wait(&c);assert_eq!(result.phase,"failed","{result:?}");assert!(result.error.unwrap().contains("cancelled"));let store=crate::component_store::Store::open(&base.join("python-tools-v2")).unwrap();assert!(store.selection().unwrap().active.is_none());assert!(!base.join("python-tools-v2/approved-tree.json").exists());assert_eq!(std::fs::read_dir(base.join("python-tools-v2/generations")).unwrap().count(),0);println!("G38_REAL_CONTROL_CANCEL_PASS");
}

#[test]fn request_get_is_read_only_even_with_start_payload(){let c=controller_new();let v=dispatch_using(&c,"GET",&serde_json::json!({"action":"start","acknowledged":true}),false,Err("missing root".into())).unwrap();assert_eq!(v["enabled"],false);assert_eq!(v["operation"]["phase"],"idle");}
#[test]fn request_gate_method_and_confirmation_fail_closed(){let c=controller_new();for (method,enabled,args) in [("POST",false,serde_json::json!({"action":"start","acknowledged":true})),("DELETE",true,serde_json::json!({})),("POST",true,serde_json::json!({"action":"start"})),("POST",true,serde_json::json!({"action":"start","acknowledged":"true"})),("POST",true,serde_json::json!({"action":"download"})),("POST",true,serde_json::json!({"action":"cancel"}))]{assert!(dispatch_using(&c,method,&args,enabled,Err("no root".into())).is_err());assert_eq!(c.status().unwrap().phase,"idle");}}
#[test]fn request_cancel_requires_matching_operation_id(){let c=controller_new();let(id,_)=c.reserve().unwrap();assert!(dispatch_using(&c,"POST",&serde_json::json!({"action":"cancel","id":"old"}),true,Err("unused".into())).is_err());let v=dispatch_using(&c,"POST",&serde_json::json!({"action":"cancel","id":id}),true,Err("unused".into())).unwrap();assert_eq!(v["operation"]["phase"],"cancelling");assert_eq!(v["operation"]["cancelRequested"],true);}
#[test]fn request_cannot_override_pinned_destination(){let c=controller_new();let args=serde_json::json!({"action":"start","acknowledged":true,"archive":"E:/archive.zip","manifest":"E:/manifest.json","components":"E:/injected","destination":"E:/injected"});assert_eq!(dispatch_using(&c,"POST",&args,true,Err("pinned root unavailable".into())).unwrap_err(),"pinned root unavailable");assert_eq!(c.status().unwrap().phase,"idle");}
