; Generated payload inventory is fixed for v2.1.0. Define the five paths/size values at compile time.
Unicode true
!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "FileFunc.nsh"
!include "x64.nsh"
!include "WinVer.nsh"

Name "FurinaKit v2.1.0"
OutFile "${OUTPUT_FILE}"
InstallDir "$LOCALAPPDATA\Programs\FurinaKit"
InstallDirRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "InstallLocation"
RequestExecutionLevel user
ManifestDPIAware true
SetCompressor /SOLID lzma
SetCompressorDictSize 64
ShowInstDetails show
ShowUninstDetails show

VIProductVersion "2.1.0.0"
VIAddVersionKey "ProductName" "FurinaKit"
VIAddVersionKey "ProductVersion" "2.1.0"
VIAddVersionKey "FileVersion" "2.1.0"
VIAddVersionKey "FileDescription" "FurinaKit v2.1.0 安装程序"
VIAddVersionKey "CompanyName" "FUFU-eng"
VIAddVersionKey "LegalCopyright" "Copyright (c) 2026 FurinaKit Contributors"

!define MUI_ICON "${PROJECT_ROOT}\src-tauri\icons\icon.ico"
!define MUI_UNICON "${PROJECT_ROOT}\src-tauri\icons\icon.ico"
!define MUI_ABORTWARNING

; Welcome Page
!define MUI_WELCOMEPAGE_TITLE "欢迎使用 FurinaKit v2.1.0 安装向导"
!define MUI_WELCOMEPAGE_TEXT "FurinaKit（芙宁娜工具箱）是一款轻量、优雅且全能的现代化 Windows 桌面工具箱。$\r$\n$\r$\n★ v2.1.0 架构升级亮点：$\r$\n1. 全新原生架构，已内置 FFmpeg 音视频引擎，装好即用$\r$\n2. 无需注册登录，无广告；离线文件在本机处理$\r$\n3. 集成 220+ 款常用工具，部分 AI 模型按需下载$\r$\n4. 全新桌面悬浮球与全局快捷键直达$\r$\n$\r$\n点击“下一步”继续安装。"
!insertmacro MUI_PAGE_WELCOME

; License Page
!define MUI_LICENSEPAGE_CHECKBOX
!define MUI_PAGE_HEADER_TEXT "软件许可与隐私协议"
!define MUI_PAGE_HEADER_SUBTEXT "请在安装 FurinaKit 前仔细阅读以下许可协议条款。"
!insertmacro MUI_PAGE_LICENSE "${PROJECT_ROOT}\packaging\LICENSE-INSTALLER.rtf"

; Directory Page
!define MUI_PAGE_HEADER_TEXT "选择安装位置"
!define MUI_PAGE_HEADER_SUBTEXT "选择 FurinaKit 的安装文件夹。"
!insertmacro MUI_PAGE_DIRECTORY

; Instfiles Page
!insertmacro MUI_PAGE_INSTFILES

; Finish Page
!define MUI_FINISHPAGE_TITLE "安装完成"
!define MUI_FINISHPAGE_TEXT "FurinaKit v2.1.0 已成功安装到您的计算机。$\r$\n$\r$\n点击“完成”退出安装向导。"
!define MUI_FINISHPAGE_RUN "$INSTDIR\FurinaKit.exe"
!define MUI_FINISHPAGE_RUN_TEXT "立即启动 FurinaKit 芙宁娜工具箱"
!insertmacro MUI_PAGE_FINISH

; Uninstaller Pages
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "English"


; ── 旧版 2.0.6（Electron）接管 ──────────────────────────────────────────
; electron-builder 用 appId com.furinakit.app 生成的卸载键
!define LEGACY_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\833dcdcd-48d4-5f29-89e5-b4d81593dd90"
!define RUN_KEY "Software\Microsoft\Windows\CurrentVersion\Run"
Var LegacyUninst
Var LegacyDir
Var LegacyAllUsers

; 从 UninstallString（形如 "X:\dir\Uninstall FurinaKit.exe" /currentuser）取出 exe 路径
Function LegacyParseUninst
  Exch $0
  Push $1
  Push $2
  Push $3
  StrCpy $1 $0 1
  ${If} $1 == '"'
    StrCpy $2 1
    loop_q:
      StrCpy $3 $0 1 $2
      ${If} $3 == ""
      ${OrIf} $3 == '"'
        Goto done_q
      ${EndIf}
      IntOp $2 $2 + 1
      Goto loop_q
    done_q:
    IntOp $2 $2 - 1
    StrCpy $0 $0 $2 1
  ${EndIf}
  Pop $3
  Pop $2
  Pop $1
  Exch $0
FunctionEnd

Function DetectLegacy
  StrCpy $LegacyUninst ""
  StrCpy $LegacyDir ""
  StrCpy $LegacyAllUsers "0"
  ReadRegStr $0 HKCU "${LEGACY_KEY}" "UninstallString"
  ${If} $0 == ""
    SetRegView 64
    ReadRegStr $0 HKLM "${LEGACY_KEY}" "UninstallString"
    ${If} $0 == ""
      SetRegView 32
      ReadRegStr $0 HKLM "${LEGACY_KEY}" "UninstallString"
    ${EndIf}
    SetRegView 32
    ${If} $0 != ""
      StrCpy $LegacyAllUsers "1"
    ${EndIf}
  ${EndIf}
  ${If} $0 == ""
    Return
  ${EndIf}
  Push $0
  Call LegacyParseUninst
  Pop $1
  ${IfNot} ${FileExists} "$1"
    ; 残留的注册表项（程序早已不在）：当前用户的顺手清掉
    ${If} $LegacyAllUsers == "0"
      DeleteRegKey HKCU "${LEGACY_KEY}"
    ${EndIf}
    Return
  ${EndIf}
  StrCpy $LegacyUninst $1
  ${GetParent} $1 $LegacyDir
FunctionEnd

Function RemoveLegacy
  ${If} $LegacyUninst == ""
    Return
  ${EndIf}
  ${If} $LegacyAllUsers == "1"
    MessageBox MB_YESNO|MB_ICONQUESTION "检测到旧版 FurinaKit 2.0.6（为所有用户安装在 $LegacyDir）。$\r$\n$\r$\n是否现在卸载旧版，释放约 600 MB 空间？$\r$\n（需要管理员确认；你的设置、收藏等数据会保留并自动导入新版）" /SD IDNO IDYES do_remove_all
    Return
    do_remove_all:
    DetailPrint "正在卸载旧版 FurinaKit 2.0.6…"
    ExecWait '"$LegacyUninst" /S /allusers _?=$LegacyDir' $0
    Delete "$LegacyUninst"
    RMDir "$LegacyDir"
    Return
  ${EndIf}
  ; 当前用户安装（默认情况）：等旧版退出后静默卸载（旧版数据保留，新版首次启动时自动导入）
  DetailPrint "正在移除旧版 FurinaKit 2.0.6（设置、收藏等数据会保留）…"
  StrCpy $1 0
  wait_old:
    ClearErrors
    FileOpen $2 "$LegacyDir\FurinaKit.exe" a
    ${IfNot} ${Errors}
      FileClose $2
      Goto old_closed
    ${EndIf}
    IntOp $1 $1 + 1
    ${If} $1 > 20
      Goto old_closed
    ${EndIf}
    Sleep 500
    Goto wait_old
  old_closed:
  ExecWait '"$LegacyUninst" /S --updated /currentuser _?=$LegacyDir' $0
  DetailPrint "旧版卸载程序返回 $0"
  Delete "$LegacyUninst"
  DeleteRegKey HKCU "${LEGACY_KEY}"
  ; 旧版遗留的开始菜单快捷方式（新版放在 FurinaKit 文件夹里）
  Delete "$SMPROGRAMS\FurinaKit.lnk"
  ; 与新版装在同一目录时，把旧版 Electron 的残留清掉（新版文件随后写入）
  ${If} ${FileExists} "$LegacyDir\resources\app\package.json"
  ${OrIf} ${FileExists} "$LegacyDir\resources\furinakit-worker.exe"
    RMDir /r "$LegacyDir\resources"
    RMDir /r "$LegacyDir\locales"
    Delete "$LegacyDir\*.pak"
    Delete "$LegacyDir\*.bin"
    Delete "$LegacyDir\*.dat"
    Delete "$LegacyDir\LICENSE.electron.txt"
    Delete "$LegacyDir\LICENSES.chromium.html"
    Delete "$LegacyDir\d3dcompiler_47.dll"
    Delete "$LegacyDir\ffmpeg.dll"
    Delete "$LegacyDir\libEGL.dll"
    Delete "$LegacyDir\libGLESv2.dll"
    Delete "$LegacyDir\vk_swiftshader.dll"
    Delete "$LegacyDir\vk_swiftshader_icd.json"
    Delete "$LegacyDir\vulkan-1.dll"
  ${EndIf}
  RMDir "$LegacyDir"
FunctionEnd

; 旧版开了「开机自启」的：把登记项换成新版（名字统一为 FurinaKit）。
; 只处理指向已安装 FurinaKit.exe 的项（开发环境里指向 electron.exe 的不动）。
Function MigrateOneAutostart
  Exch $0
  ReadRegStr $1 HKCU "${RUN_KEY}" $0
  ${If} $1 != ""
    Push $1
    Call LegacyParseUninst
    Pop $2
    StrCpy $3 $2 13 -13
    ${If} $3 == "FurinaKit.exe"
      DeleteRegValue HKCU "${RUN_KEY}" $0
      WriteRegStr HKCU "${RUN_KEY}" "FurinaKit" '"$INSTDIR\FurinaKit.exe"'
    ${EndIf}
  ${EndIf}
  Pop $0
FunctionEnd

Function MigrateLegacyAutostart
  Push "furinakit.desktop.app"
  Call MigrateOneAutostart
  Push "com.furinakit.app"
  Call MigrateOneAutostart
FunctionEnd

Function .onInit
  SetShellVarContext current
  ${IfNot} ${RunningX64}
    MessageBox MB_OK|MB_ICONSTOP "FurinaKit 需要 64 位 Windows 系统 (Windows x64)。"
    SetErrorLevel 2
    Abort
  ${EndIf}
  ${IfNot} ${AtLeastWin10}
    MessageBox MB_OK|MB_ICONSTOP "FurinaKit 需要 Windows 10 或 Windows 11。"
    SetErrorLevel 2
    Abort
  ${EndIf}
  Call DetectLegacy
  ReadRegStr $0 HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "InstallLocation"
  ${If} $0 == ""
  ${AndIf} $LegacyDir != ""
  ${AndIf} $LegacyAllUsers == "0"
    StrCpy $INSTDIR $LegacyDir
  ${EndIf}
FunctionEnd

Function EnsureNotRunning
check_again:
  System::Call 'kernel32::OpenMutexW(i 0x00100000, i 0, w "furinakit-single-instance-normal") p.r0'
  ${If} $0 != 0
    System::Call 'kernel32::CloseHandle(p r0)'
    MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "FurinaKit 正在运行中。$\r$\n$\r$\n请从系统托盘右键退出 FurinaKit 后点击“重试”；$\r$\n本程序不会强制关闭您的其它软件或未保存任务。" IDRETRY check_again
    SetErrorLevel 2
    Abort
  ${EndIf}
FunctionEnd

Function EnsureWebView2
  SetRegView 64
  ReadRegStr $0 HKLM "SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
  ${If} $0 != ""
    Goto webview_ready
  ${EndIf}
  ReadRegStr $0 HKCU "SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
  ${If} $0 != ""
    Goto webview_ready
  ${EndIf}
  SetRegView 32
  ReadRegStr $0 HKLM "SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
  ${If} $0 != ""
    Goto webview_ready
  ${EndIf}
  ReadRegStr $0 HKCU "SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
  ${If} $0 != ""
    Goto webview_ready
  ${EndIf}
  DetailPrint "正在配置 Microsoft WebView2 运行时..."
  InitPluginsDir
  SetOutPath "$PLUGINSDIR"
  File /oname=MicrosoftEdgeWebview2Setup.exe "${WEBVIEW_BOOTSTRAPPER}"
  ExecWait '"$PLUGINSDIR\MicrosoftEdgeWebview2Setup.exe" /silent /install' $0
  ${If} $0 != 0
  ${AndIf} $0 != 3010
    MessageBox MB_OK|MB_ICONSTOP "WebView2 运行时配置失败 ($0)。请检查网络连接或手动安装 Microsoft WebView2 运行时后重试。" /SD IDOK
    SetErrorLevel 3
    Abort
  ${EndIf}
webview_ready:
  SetRegView 32
FunctionEnd

Section "FurinaKit" Main
  Call EnsureNotRunning
  Call EnsureWebView2
  Call RemoveLegacy

  SetOverwrite on
  SetOutPath "$INSTDIR"
  File "${PAYLOAD_DIR}\DIRECTML-LICENSE.txt"
  File "${PAYLOAD_DIR}\DIRECTML-SOURCE.json"
  File "${PAYLOAD_DIR}\DirectML.dll"
  File "${PAYLOAD_DIR}\FurinaKit-runtime.json"
  File "${PAYLOAD_DIR}\FurinaKit-files.json"
  File "${PAYLOAD_DIR}\FurinaKit.exe"
  File "${PAYLOAD_DIR}\LICENSE"
  File "${PAYLOAD_DIR}\MSVC-RUNTIME-NOTICE.txt"
  File "${PAYLOAD_DIR}\README.txt"
  File "${PAYLOAD_DIR}\THIRD_PARTY_NOTICES.md"
  File "${PAYLOAD_DIR}\furinakit-image-worker.exe"
  SetOutPath "$INSTDIR\licenses\ffmpeg"
  File "${PAYLOAD_DIR}\licenses\ffmpeg\LICENSE.txt"
  File "${PAYLOAD_DIR}\licenses\ffmpeg\README.txt"
  File "${PAYLOAD_DIR}\licenses\ffmpeg\SOURCE.json"
  File "${PAYLOAD_DIR}\licenses\ffmpeg\UPSTREAM-LICENSE.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\blake3-CC0.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\clipboard-rs-MIT.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\curl-v7-test-toolchain-notices.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\gif-MIT.txt"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\README.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1\LICENSE-0BSD"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\aligned-0.4.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\aligned-0.4.3\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\aligned-0.4.3\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\aligned-vec-0.6.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\aligned-vec-0.6.4\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\anyhow-1.0.104"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\anyhow-1.0.104\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\anyhow-1.0.104\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\arg_enum_proc_macro-0.3.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\arg_enum_proc_macro-0.3.4\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\arrayvec-0.7.8"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\arrayvec-0.7.8\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\arrayvec-0.7.8\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\as-slice-0.2.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\as-slice-0.2.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\as-slice-0.2.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\assert_matches-1.5.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\assert_matches-1.5.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\assert_matches-1.5.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-0.4.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\atomig-0.4.3\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\atomig-0.4.3\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-macro-0.4.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\atomig-macro-0.4.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\atomig-macro-0.4.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\autocfg-1.5.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\autocfg-1.5.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\autocfg-1.5.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\av-scenechange-0.14.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\av-scenechange-0.14.1\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\av1-grain-0.2.5"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\av1-grain-0.2.5\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-container-adapter\vendor\libavif"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\avif-container-adapter\vendor\libavif\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-serialize-0.8.9"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\avif-serialize-0.8.9\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitflags-2.13.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bitflags-2.13.2\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bitflags-2.13.2\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitstream-io-4.10.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bitstream-io-4.10.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bitstream-io-4.10.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\built-0.8.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\built-0.8.1\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bumpalo-3.20.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bumpalo-3.20.3\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bumpalo-3.20.3\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2\LICENSE-MIT"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2\LICENSE-ZLIB"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\byteorder-1.5.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\byteorder-1.5.0\COPYING"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\byteorder-1.5.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\byteorder-lite-0.1.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\byteorder-lite-0.1.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cc-1.4.7"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\cc-1.4.7\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\cc-1.4.7\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cfg-if-1.0.5"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\cfg-if-1.0.5\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\cfg-if-1.0.5\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\color_quant-1.1.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\color_quant-1.1.0\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\compatibility-g04.json"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crc32fast-1.5.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crc32fast-1.5.2\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crc32fast-1.5.2\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-deque-0.8.8"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crossbeam-deque-0.8.8\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crossbeam-deque-0.8.8\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-epoch-0.9.21"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crossbeam-epoch-0.9.21\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crossbeam-epoch-0.9.21\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-utils-0.8.23"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crossbeam-utils-0.8.23\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\crossbeam-utils-0.8.23\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\either-1.18.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\either-1.18.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\either-1.18.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\equator-0.4.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\equator-0.4.2\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\equator-macro-0.4.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\equator-macro-0.4.2\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\fax-0.2.7"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\fax-0.2.7\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\fdeflate-0.3.7"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\fdeflate-0.3.7\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\fdeflate-0.3.7\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\find-msvc-tools-0.1.13"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\find-msvc-tools-0.1.13\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\find-msvc-tools-0.1.13\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\flate2-1.1.10"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\flate2-1.1.10\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\flate2-1.1.10\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\getrandom-0.4.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\getrandom-0.4.3\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\getrandom-0.4.3\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\gif-0.14.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\gif-0.14.2\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\gif-0.14.2\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\glob-0.3.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\glob-0.3.4\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\glob-0.3.4\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\half-2.7.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\half-2.7.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\half-2.7.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\heck-0.5.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\heck-0.5.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\heck-0.5.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-0.25.10"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\image-0.25.10\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\image-0.25.10\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-webp-0.2.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\image-webp-0.2.4\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\image-webp-0.2.4\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\imgref-1.12.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\imgref-1.12.3\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\imgref-1.12.3\LICENSE-CC0"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itertools-0.14.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\itertools-0.14.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\itertools-0.14.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itoa-1.0.18"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\itoa-1.0.18\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\itoa-1.0.18\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\jobserver-0.1.35"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\jobserver-0.1.35\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\jobserver-0.1.35\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libc-0.2.189"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\libc-0.2.189\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\libc-0.2.189\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libwebp-sys-0.9.6\vendor"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\libwebp-sys-0.9.6\vendor\COPYING"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\libwebp-sys-0.9.6\vendor\PATENTS"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\lock_api-0.4.14"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\lock_api-0.4.14\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\lock_api-0.4.14\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\log-0.4.34"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\log-0.4.34\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\log-0.4.34\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\loop9-0.1.5"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\loop9-0.1.5\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\manifest.json"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\maybe-rayon-0.1.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\maybe-rayon-0.1.1\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\memchr-2.8.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\memchr-2.8.3\COPYING"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\memchr-2.8.3\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE-APACHE.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE-MIT.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE-ZLIB.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE-APACHE.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE-MIT.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE-ZLIB.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\moxcms-0.8.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\moxcms-0.8.1\LICENSE-APACHE.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\moxcms-0.8.1\LICENSE.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\nasm-rs-0.3.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\nasm-rs-0.3.2\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\nasm-rs-0.3.2\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\new_debug_unreachable-1.0.6"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\new_debug_unreachable-1.0.6\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\no_std_io2-0.9.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\no_std_io2-0.9.4\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\no_std_io2-0.9.4\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\nom-8.0.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\nom-8.0.0\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\noop_proc_macro-0.3.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\noop_proc_macro-0.3.0\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-bigint-0.4.8"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-bigint-0.4.8\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-bigint-0.4.8\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-derive-0.4.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-derive-0.4.2\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-derive-0.4.2\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-integer-0.1.47"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-integer-0.1.47\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-integer-0.1.47\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-rational-0.4.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-rational-0.4.2\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-rational-0.4.2\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-traits-0.2.19"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-traits-0.2.19\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\num-traits-0.2.19\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\once_cell-1.21.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\once_cell-1.21.4\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\once_cell-1.21.4\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot-0.12.5"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\parking_lot-0.12.5\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\parking_lot-0.12.5\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot_core-0.9.12"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\parking_lot_core-0.9.12\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\parking_lot_core-0.9.12\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\paste-1.0.15"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\paste-1.0.15\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\paste-1.0.15\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pastey-0.1.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\pastey-0.1.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\pastey-0.1.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\png-0.18.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\png-0.18.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\png-0.18.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\proc-macro2-1.0.107"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\proc-macro2-1.0.107\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\proc-macro2-1.0.107\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-1.0.18"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\profiling-1.0.18\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\profiling-1.0.18\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-procmacros-1.0.18"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\profiling-procmacros-1.0.18\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\profiling-procmacros-1.0.18\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pxfm-0.1.30"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\pxfm-0.1.30\LICENSE-APACHE.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\pxfm-0.1.30\LICENSE.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quick-error-2.0.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\quick-error-2.0.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\quick-error-2.0.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quote-1.0.47"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\quote-1.0.47\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\quote-1.0.47\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rav1d-1.1.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rav1d-1.1.0\COPYING"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rav1e-0.8.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rav1e-0.8.1\LICENSE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rav1e-0.8.1\PATENTS"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\ravif-0.13.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\ravif-0.13.0\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\raw-cpuid-11.6.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\raw-cpuid-11.6.0\LICENSE.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-1.12.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rayon-1.12.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rayon-1.12.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-core-1.13.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rayon-core-1.13.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rayon-core-1.13.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rgb-0.8.53"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rgb-0.8.53\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rustversion-1.0.23"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rustversion-1.0.23\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\rustversion-1.0.23\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\scopeguard-1.2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\scopeguard-1.2.0\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\scopeguard-1.2.0\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde-1.0.229"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde-1.0.229\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde-1.0.229\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_core-1.0.229"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde_core-1.0.229\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde_core-1.0.229\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_derive-1.0.229"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde_derive-1.0.229\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde_derive-1.0.229\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_json-1.0.151"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde_json-1.0.151\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\serde_json-1.0.151\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\shlex-2.0.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\shlex-2.0.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\shlex-2.0.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\simd-adler32-0.3.10"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\simd-adler32-0.3.10\LICENSE.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\simd_helpers-0.1.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\simd_helpers-0.1.0\Cargo.toml.upstream.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\simd_helpers-0.1.0\NOTICE-MIT.txt"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\smallvec-1.16.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\smallvec-1.16.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\smallvec-1.16.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\sources"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\sources\rav1d-1.1.0.crate"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\stable_deref_trait-1.2.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\stable_deref_trait-1.2.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\stable_deref_trait-1.2.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\strum-0.26.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\strum-0.26.3\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\strum_macros-0.26.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\strum_macros-0.26.4\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-2.0.119"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\syn-2.0.119\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\syn-2.0.119\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-3.0.6"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\syn-3.0.6\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\syn-3.0.6\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-2.0.20"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\thiserror-2.0.20\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\thiserror-2.0.20\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-impl-2.0.20"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\thiserror-impl-2.0.20\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\thiserror-impl-2.0.20\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3\tests"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3\tests\COPYRIGHT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\to_method-1.1.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\to_method-1.1.0\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26\LICENSE-MIT"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26\LICENSE-UNICODE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\v_frame-0.3.9"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\v_frame-0.3.9\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-0.2.128"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-0.2.128\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-0.2.128\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-0.2.128"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-0.2.128\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-0.2.128\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-support-0.2.128"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-support-0.2.128\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-support-0.2.128\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-shared-0.2.128"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-shared-0.2.128\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-shared-0.2.128\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\webp-0.3.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\webp-0.3.1\COPYRIGHT"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\webp-0.3.1\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\webp-0.3.1\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\weezl-0.1.12"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\weezl-0.1.12\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\weezl-0.1.12\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-0.61.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-0.61.3\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-0.61.3\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-collections-0.2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-collections-0.2.0\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-collections-0.2.0\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-core-0.61.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-core-0.61.2\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-core-0.61.2\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-future-0.2.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-future-0.2.1\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-future-0.2.1\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-implement-0.60.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-implement-0.60.2\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-implement-0.60.2\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-interface-0.59.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-interface-0.59.3\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-interface-0.59.3\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.1.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-link-0.1.3\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-link-0.1.3\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.2.1"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-link-0.2.1\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-link-0.2.1\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-numerics-0.2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-numerics-0.2.0\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-numerics-0.2.0\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-result-0.3.4"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-result-0.3.4\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-result-0.3.4\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-strings-0.4.2"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-strings-0.4.2\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-strings-0.4.2\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-threading-0.1.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-threading-0.1.0\license-apache-2.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\windows-threading-0.1.0\license-mit"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\y4m-0.8.0"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\y4m-0.8.0\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\LICENSE-BSD"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src\third_party\rust"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src\third_party\rust\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src\third_party\rust\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57\LICENSE-BSD"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35\LICENSE-BSD"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57\LICENSE-BSD"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zlib-rs-0.6.7"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zlib-rs-0.6.7\LICENSE"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zmij-1.0.23"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zmij-1.0.23\LICENSE-MIT"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3\LICENSE-MIT"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3\LICENSE-ZLIB"
  SetOutPath "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15\LICENSE-APACHE"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15\LICENSE-MIT"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15\LICENSE-ZLIB"
  SetOutPath "$INSTDIR\licenses\project-dependencies"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\imageproc-contours-LICENSE.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\ocr-Apache-2.0-LICENSE.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\ocr-NOTICE.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\rusqlite-MIT.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\types-v4-dependency-notices.md"
  SetOutPath "$INSTDIR\licenses\project-dependencies\upscale-lite"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\upscale-lite\NOTICE.md"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\upscale-lite\Real-ESRGAN-LICENSE.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\upscale-lite\Real-ESRGAN-ncnn-vulkan-LICENSE.txt"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\upscale-lite\UPSTREAM-SOURCES.json"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\upscale-lite\ncnn-LICENSE.txt"
  SetOutPath "$INSTDIR\licenses\project-dependencies"
  File "${PAYLOAD_DIR}\licenses\project-dependencies\windows-MIT.txt"
  SetOutPath "$INSTDIR\models\ocr-v3"
  File "${PAYLOAD_DIR}\models\ocr-v3\ch_PP-OCRv3_det_infer.onnx"
  File "${PAYLOAD_DIR}\models\ocr-v3\ch_PP-OCRv3_rec_infer.onnx"
  File "${PAYLOAD_DIR}\models\ocr-v3\ch_ppocr_mobile_v2.0_cls_infer.onnx"
  File "${PAYLOAD_DIR}\models\ocr-v3\manifest.json"
  SetOutPath "$INSTDIR"
  File "${PAYLOAD_DIR}\msvcp140.dll"
  File "${PAYLOAD_DIR}\msvcp140_1.dll"
  SetOutPath "$INSTDIR\tools\archpr"
  File "${PAYLOAD_DIR}\tools\archpr\elcom_reg.dll"
  File "${PAYLOAD_DIR}\tools\archpr\elcom_xml.dll"
  File "${PAYLOAD_DIR}\tools\archpr\elcom_lang.xml"
  File "${PAYLOAD_DIR}\tools\archpr\elcom_partners.exml"
  File "${PAYLOAD_DIR}\tools\archpr\runtime-manifest.json"
  File "${PAYLOAD_DIR}\tools\archpr\BUNDLED-NOTICE.md"
  File "${PAYLOAD_DIR}\tools\archpr\ARCHPR.chm"
  File "${PAYLOAD_DIR}\tools\archpr\ARCHPR.exe"
  File "${PAYLOAD_DIR}\tools\archpr\chinese_simp.lng"
  File "${PAYLOAD_DIR}\tools\archpr\digits.chr"
  File "${PAYLOAD_DIR}\tools\archpr\english.chr"
  File "${PAYLOAD_DIR}\tools\archpr\english.dic"
  File "${PAYLOAD_DIR}\tools\archpr\english.lng"
  File "${PAYLOAD_DIR}\tools\archpr\german.chr"
  File "${PAYLOAD_DIR}\tools\archpr\german.dic"
  File "${PAYLOAD_DIR}\tools\archpr\german.lng"
  File "${PAYLOAD_DIR}\tools\archpr\russian.chr"
  File "${PAYLOAD_DIR}\tools\archpr\russian.dic"
  File "${PAYLOAD_DIR}\tools\archpr\russian.lng"
  File "${PAYLOAD_DIR}\tools\archpr\special.chr"
  SetOutPath "$INSTDIR\tools\engines\aria2"
  File "${PAYLOAD_DIR}\tools\engines\aria2\AUTHORS"
  File "${PAYLOAD_DIR}\tools\engines\aria2\COPYING"
  File "${PAYLOAD_DIR}\tools\engines\aria2\LICENSE.OpenSSL"
  File "${PAYLOAD_DIR}\tools\engines\aria2\README.html"
  File "${PAYLOAD_DIR}\tools\engines\aria2\README.mingw"
  File "${PAYLOAD_DIR}\tools\engines\aria2\SOURCE.txt"
  File "${PAYLOAD_DIR}\tools\engines\aria2\aria2c.exe"
  SetOutPath "$INSTDIR\tools\engines\ffmpeg"
  File "${PAYLOAD_DIR}\tools\engines\ffmpeg\ffmpeg.exe"
  File "${PAYLOAD_DIR}\tools\engines\ffmpeg\ffprobe.exe"
  SetOutPath "$INSTDIR\tools\engines\yt-dlp"
  File "${PAYLOAD_DIR}\tools\engines\yt-dlp\yt-dlp.exe"
  SetOutPath "$INSTDIR\licenses\yt-dlp"
  File "${PAYLOAD_DIR}\licenses\yt-dlp\LICENSE.txt"
  File "${PAYLOAD_DIR}\licenses\yt-dlp\SOURCE.json"
  File "${PAYLOAD_DIR}\licenses\yt-dlp\THIRD_PARTY_LICENSES.txt"
  SetOutPath "$INSTDIR\tools\engines\upscale-lite\models"
  File "${PAYLOAD_DIR}\tools\engines\upscale-lite\models\realesr-animevideov3-x2.bin"
  File "${PAYLOAD_DIR}\tools\engines\upscale-lite\models\realesr-animevideov3-x2.param"
  File "${PAYLOAD_DIR}\tools\engines\upscale-lite\models\realesr-animevideov3-x3.bin"
  File "${PAYLOAD_DIR}\tools\engines\upscale-lite\models\realesr-animevideov3-x3.param"
  SetOutPath "$INSTDIR\tools\engines\upscale-lite"
  File "${PAYLOAD_DIR}\tools\engines\upscale-lite\realesrgan-ncnn-vulkan.exe"
  SetOutPath "$INSTDIR\tools\engines\whisper"
  File "${PAYLOAD_DIR}\tools\engines\whisper\LICENSE.txt"
  File "${PAYLOAD_DIR}\tools\engines\whisper\MSVC-RUNTIME-NOTICE.txt"
  File "${PAYLOAD_DIR}\tools\engines\whisper\SOURCE.txt"
  File "${PAYLOAD_DIR}\tools\engines\whisper\ggml-base.dll"
  File "${PAYLOAD_DIR}\tools\engines\whisper\ggml-cpu.dll"
  File "${PAYLOAD_DIR}\tools\engines\whisper\ggml.dll"
  File "${PAYLOAD_DIR}\tools\engines\whisper\msvcp140.dll"
  File "${PAYLOAD_DIR}\tools\engines\whisper\vcomp140.dll"
  File "${PAYLOAD_DIR}\tools\engines\whisper\vcruntime140.dll"
  File "${PAYLOAD_DIR}\tools\engines\whisper\vcruntime140_1.dll"
  File "${PAYLOAD_DIR}\tools\engines\whisper\whisper-cli.exe"
  File "${PAYLOAD_DIR}\tools\engines\whisper\whisper.dll"
  SetOutPath "$INSTDIR"
  File "${PAYLOAD_DIR}\vcomp140.dll"
  File "${PAYLOAD_DIR}\vcruntime140.dll"
  File "${PAYLOAD_DIR}\vcruntime140_1.dll"

  SetOutPath "$INSTDIR"
  WriteUninstaller "$INSTDIR\Uninstall FurinaKit.exe"

  ; Create Shortcuts
  CreateDirectory "$SMPROGRAMS\FurinaKit"
  CreateShortcut "$SMPROGRAMS\FurinaKit\FurinaKit.lnk" "$INSTDIR\FurinaKit.exe" "" "$INSTDIR\FurinaKit.exe" 0
  CreateShortcut "$DESKTOP\FurinaKit.lnk" "$INSTDIR\FurinaKit.exe" "" "$INSTDIR\FurinaKit.exe" 0

  ; Add/Remove Programs Registry Keys
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "DisplayName" "FurinaKit 芙宁娜工具箱"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "DisplayVersion" "2.1.0"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "Publisher" "FUFU-eng"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "DisplayIcon" "$INSTDIR\FurinaKit.exe,0"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "UninstallString" '$\"$INSTDIR\Uninstall FurinaKit.exe$\"'
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "QuietUninstallString" '$\"$INSTDIR\Uninstall FurinaKit.exe$\" /S'
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "URLInfoAbout" "https://github.com/FUFU-eng/FurinaKit"
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "EstimatedSize" ${INSTALLED_SIZE_KB}
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "NoModify" 1
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit" "NoRepair" 1

  Call MigrateLegacyAutostart
SectionEnd

Function un.onInit
  SetShellVarContext current
check_un_again:
  System::Call 'kernel32::OpenMutexW(i 0x00100000, i 0, w "furinakit-single-instance-normal") p.r0'
  ${If} $0 != 0
    System::Call 'kernel32::CloseHandle(p r0)'
    MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "请先从托盘退出 FurinaKit，再进行卸载。" IDRETRY check_un_again
    SetErrorLevel 2
    Abort
  ${EndIf}
FunctionEnd

Section "Uninstall"
  SetRegView 32
  ReadRegStr $0 HKCU "Software\ElcomSoft\Common Files" "Location"
  StrCmp $0 "$INSTDIR\tools\archpr" 0 archpr_shared_cleanup_done
    DeleteRegValue HKCU "Software\ElcomSoft\Common Files" "Location"
    DeleteRegKey /ifempty HKCU "Software\ElcomSoft\Common Files"
  archpr_shared_cleanup_done:
  SetRegView lastused

  Delete "$INSTDIR\DIRECTML-LICENSE.txt"
  Delete "$INSTDIR\DIRECTML-SOURCE.json"
  Delete "$INSTDIR\DirectML.dll"
  Delete "$INSTDIR\FurinaKit-runtime.json"
  Delete "$INSTDIR\FurinaKit-files.json"
  Delete "$INSTDIR\FurinaKit.exe"
  Delete "$INSTDIR\LICENSE"
  Delete "$INSTDIR\MSVC-RUNTIME-NOTICE.txt"
  Delete "$INSTDIR\README.txt"
  Delete "$INSTDIR\THIRD_PARTY_NOTICES.md"
  Delete "$INSTDIR\furinakit-image-worker.exe"
  Delete "$INSTDIR\licenses\ffmpeg\LICENSE.txt"
  Delete "$INSTDIR\licenses\ffmpeg\README.txt"
  Delete "$INSTDIR\licenses\ffmpeg\SOURCE.json"
  Delete "$INSTDIR\licenses\ffmpeg\UPSTREAM-LICENSE.md"
  Delete "$INSTDIR\licenses\project-dependencies\blake3-CC0.txt"
  Delete "$INSTDIR\licenses\project-dependencies\clipboard-rs-MIT.txt"
  Delete "$INSTDIR\licenses\project-dependencies\curl-v7-test-toolchain-notices.md"
  Delete "$INSTDIR\licenses\project-dependencies\gif-MIT.txt"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\README.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1\LICENSE-0BSD"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\aligned-0.4.3\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\aligned-0.4.3\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\aligned-vec-0.6.4\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\anyhow-1.0.104\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\anyhow-1.0.104\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\arg_enum_proc_macro-0.3.4\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\arrayvec-0.7.8\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\arrayvec-0.7.8\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\as-slice-0.2.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\as-slice-0.2.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\assert_matches-1.5.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\assert_matches-1.5.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-0.4.3\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-0.4.3\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-macro-0.4.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-macro-0.4.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\autocfg-1.5.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\autocfg-1.5.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\av-scenechange-0.14.1\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\av1-grain-0.2.5\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-container-adapter\vendor\libavif\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-serialize-0.8.9\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitflags-2.13.2\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitflags-2.13.2\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitstream-io-4.10.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitstream-io-4.10.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\built-0.8.1\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bumpalo-3.20.3\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bumpalo-3.20.3\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2\LICENSE-ZLIB"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\byteorder-1.5.0\COPYING"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\byteorder-1.5.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\byteorder-lite-0.1.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cc-1.4.7\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cc-1.4.7\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cfg-if-1.0.5\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cfg-if-1.0.5\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\color_quant-1.1.0\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\compatibility-g04.json"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crc32fast-1.5.2\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crc32fast-1.5.2\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-deque-0.8.8\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-deque-0.8.8\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-epoch-0.9.21\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-epoch-0.9.21\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-utils-0.8.23\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-utils-0.8.23\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\either-1.18.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\either-1.18.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\equator-0.4.2\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\equator-macro-0.4.2\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\fax-0.2.7\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\fdeflate-0.3.7\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\fdeflate-0.3.7\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\find-msvc-tools-0.1.13\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\find-msvc-tools-0.1.13\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\flate2-1.1.10\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\flate2-1.1.10\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\getrandom-0.4.3\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\getrandom-0.4.3\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\gif-0.14.2\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\gif-0.14.2\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\glob-0.3.4\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\glob-0.3.4\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\half-2.7.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\half-2.7.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\heck-0.5.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\heck-0.5.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-0.25.10\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-0.25.10\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-webp-0.2.4\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-webp-0.2.4\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\imgref-1.12.3\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\imgref-1.12.3\LICENSE-CC0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itertools-0.14.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itertools-0.14.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itoa-1.0.18\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itoa-1.0.18\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\jobserver-0.1.35\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\jobserver-0.1.35\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libc-0.2.189\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libc-0.2.189\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libwebp-sys-0.9.6\vendor\COPYING"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libwebp-sys-0.9.6\vendor\PATENTS"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\lock_api-0.4.14\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\lock_api-0.4.14\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\log-0.4.34\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\log-0.4.34\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\loop9-0.1.5\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\manifest.json"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\maybe-rayon-0.1.1\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\memchr-2.8.3\COPYING"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\memchr-2.8.3\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE-APACHE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE-MIT.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9\LICENSE-ZLIB.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE-APACHE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE-MIT.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1\LICENSE-ZLIB.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\moxcms-0.8.1\LICENSE-APACHE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\moxcms-0.8.1\LICENSE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\nasm-rs-0.3.2\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\nasm-rs-0.3.2\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\new_debug_unreachable-1.0.6\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\no_std_io2-0.9.4\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\no_std_io2-0.9.4\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\nom-8.0.0\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\noop_proc_macro-0.3.0\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-bigint-0.4.8\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-bigint-0.4.8\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-derive-0.4.2\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-derive-0.4.2\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-integer-0.1.47\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-integer-0.1.47\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-rational-0.4.2\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-rational-0.4.2\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-traits-0.2.19\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-traits-0.2.19\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\once_cell-1.21.4\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\once_cell-1.21.4\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot-0.12.5\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot-0.12.5\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot_core-0.9.12\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot_core-0.9.12\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\paste-1.0.15\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\paste-1.0.15\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pastey-0.1.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pastey-0.1.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\png-0.18.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\png-0.18.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\proc-macro2-1.0.107\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\proc-macro2-1.0.107\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-1.0.18\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-1.0.18\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-procmacros-1.0.18\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-procmacros-1.0.18\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pxfm-0.1.30\LICENSE-APACHE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pxfm-0.1.30\LICENSE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quick-error-2.0.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quick-error-2.0.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quote-1.0.47\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quote-1.0.47\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rav1d-1.1.0\COPYING"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rav1e-0.8.1\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rav1e-0.8.1\PATENTS"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\ravif-0.13.0\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\raw-cpuid-11.6.0\LICENSE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-1.12.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-1.12.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-core-1.13.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-core-1.13.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rgb-0.8.53\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rustversion-1.0.23\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rustversion-1.0.23\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\scopeguard-1.2.0\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\scopeguard-1.2.0\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde-1.0.229\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde-1.0.229\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_core-1.0.229\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_core-1.0.229\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_derive-1.0.229\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_derive-1.0.229\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_json-1.0.151\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_json-1.0.151\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\shlex-2.0.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\shlex-2.0.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\simd-adler32-0.3.10\LICENSE.md"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\simd_helpers-0.1.0\Cargo.toml.upstream.txt"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\simd_helpers-0.1.0\NOTICE-MIT.txt"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\smallvec-1.16.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\smallvec-1.16.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\sources\rav1d-1.1.0.crate"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\stable_deref_trait-1.2.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\stable_deref_trait-1.2.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\strum-0.26.3\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\strum_macros-0.26.4\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-2.0.119\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-2.0.119\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-3.0.6\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-3.0.6\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-2.0.20\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-2.0.20\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-impl-2.0.20\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-impl-2.0.20\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3\tests\COPYRIGHT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\to_method-1.1.0\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26\LICENSE-UNICODE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\v_frame-0.3.9\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-0.2.128\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-0.2.128\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-0.2.128\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-0.2.128\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-support-0.2.128\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-support-0.2.128\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-shared-0.2.128\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-shared-0.2.128\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\webp-0.3.1\COPYRIGHT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\webp-0.3.1\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\webp-0.3.1\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\weezl-0.1.12\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\weezl-0.1.12\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-0.61.3\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-0.61.3\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-collections-0.2.0\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-collections-0.2.0\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-core-0.61.2\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-core-0.61.2\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-future-0.2.1\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-future-0.2.1\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-implement-0.60.2\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-implement-0.60.2\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-interface-0.59.3\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-interface-0.59.3\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.1.3\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.1.3\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.2.1\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.2.1\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-numerics-0.2.0\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-numerics-0.2.0\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-result-0.3.4\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-result-0.3.4\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-strings-0.4.2\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-strings-0.4.2\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-threading-0.1.0\license-apache-2.0"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-threading-0.1.0\license-mit"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\y4m-0.8.0\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\LICENSE-BSD"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src\third_party\rust\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src\third_party\rust\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57\LICENSE-BSD"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35\LICENSE-BSD"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57\LICENSE-BSD"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zlib-rs-0.6.7\LICENSE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zmij-1.0.23\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3\LICENSE-ZLIB"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15\LICENSE-APACHE"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15\LICENSE-MIT"
  Delete "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15\LICENSE-ZLIB"
  Delete "$INSTDIR\licenses\project-dependencies\imageproc-contours-LICENSE.txt"
  Delete "$INSTDIR\licenses\project-dependencies\ocr-Apache-2.0-LICENSE.txt"
  Delete "$INSTDIR\licenses\project-dependencies\ocr-NOTICE.md"
  Delete "$INSTDIR\licenses\project-dependencies\rusqlite-MIT.txt"
  Delete "$INSTDIR\licenses\project-dependencies\types-v4-dependency-notices.md"
  Delete "$INSTDIR\licenses\project-dependencies\upscale-lite\NOTICE.md"
  Delete "$INSTDIR\licenses\project-dependencies\upscale-lite\Real-ESRGAN-LICENSE.txt"
  Delete "$INSTDIR\licenses\project-dependencies\upscale-lite\Real-ESRGAN-ncnn-vulkan-LICENSE.txt"
  Delete "$INSTDIR\licenses\project-dependencies\upscale-lite\UPSTREAM-SOURCES.json"
  Delete "$INSTDIR\licenses\project-dependencies\upscale-lite\ncnn-LICENSE.txt"
  Delete "$INSTDIR\licenses\project-dependencies\windows-MIT.txt"
  Delete "$INSTDIR\models\ocr-v3\ch_PP-OCRv3_det_infer.onnx"
  Delete "$INSTDIR\models\ocr-v3\ch_PP-OCRv3_rec_infer.onnx"
  Delete "$INSTDIR\models\ocr-v3\ch_ppocr_mobile_v2.0_cls_infer.onnx"
  Delete "$INSTDIR\models\ocr-v3\manifest.json"
  Delete "$INSTDIR\msvcp140.dll"
  Delete "$INSTDIR\msvcp140_1.dll"
  Delete "$INSTDIR\tools\archpr\ARCHPR.chm"
  Delete "$INSTDIR\tools\archpr\ARCHPR.exe"
  Delete "$INSTDIR\tools\archpr\elcom_reg.dll"
  Delete "$INSTDIR\tools\archpr\elcom_xml.dll"
  Delete "$INSTDIR\tools\archpr\elcom_lang.xml"
  Delete "$INSTDIR\tools\archpr\elcom_partners.exml"
  Delete "$INSTDIR\tools\archpr\runtime-manifest.json"
  Delete "$INSTDIR\tools\archpr\BUNDLED-NOTICE.md"
  Delete "$INSTDIR\tools\archpr\chinese_simp.lng"
  Delete "$INSTDIR\tools\archpr\digits.chr"
  Delete "$INSTDIR\tools\archpr\english.chr"
  Delete "$INSTDIR\tools\archpr\english.dic"
  Delete "$INSTDIR\tools\archpr\english.lng"
  Delete "$INSTDIR\tools\archpr\german.chr"
  Delete "$INSTDIR\tools\archpr\german.dic"
  Delete "$INSTDIR\tools\archpr\german.lng"
  Delete "$INSTDIR\tools\archpr\russian.chr"
  Delete "$INSTDIR\tools\archpr\russian.dic"
  Delete "$INSTDIR\tools\archpr\russian.lng"
  Delete "$INSTDIR\tools\archpr\special.chr"
  Delete "$INSTDIR\tools\engines\aria2\AUTHORS"
  Delete "$INSTDIR\tools\engines\aria2\COPYING"
  Delete "$INSTDIR\tools\engines\aria2\LICENSE.OpenSSL"
  Delete "$INSTDIR\tools\engines\aria2\README.html"
  Delete "$INSTDIR\tools\engines\aria2\README.mingw"
  Delete "$INSTDIR\tools\engines\aria2\SOURCE.txt"
  Delete "$INSTDIR\tools\engines\aria2\aria2c.exe"
  Delete "$INSTDIR\tools\engines\ffmpeg\ffmpeg.exe"
  Delete "$INSTDIR\tools\engines\ffmpeg\ffprobe.exe"
  Delete "$INSTDIR\tools\engines\yt-dlp\yt-dlp.exe"
  Delete "$INSTDIR\licenses\yt-dlp\LICENSE.txt"
  Delete "$INSTDIR\licenses\yt-dlp\SOURCE.json"
  Delete "$INSTDIR\licenses\yt-dlp\THIRD_PARTY_LICENSES.txt"
  Delete "$INSTDIR\tools\engines\upscale-lite\models\realesr-animevideov3-x2.bin"
  Delete "$INSTDIR\tools\engines\upscale-lite\models\realesr-animevideov3-x2.param"
  Delete "$INSTDIR\tools\engines\upscale-lite\models\realesr-animevideov3-x3.bin"
  Delete "$INSTDIR\tools\engines\upscale-lite\models\realesr-animevideov3-x3.param"
  Delete "$INSTDIR\tools\engines\upscale-lite\realesrgan-ncnn-vulkan.exe"
  Delete "$INSTDIR\tools\engines\whisper\LICENSE.txt"
  Delete "$INSTDIR\tools\engines\whisper\MSVC-RUNTIME-NOTICE.txt"
  Delete "$INSTDIR\tools\engines\whisper\SOURCE.txt"
  Delete "$INSTDIR\tools\engines\whisper\ggml-base.dll"
  Delete "$INSTDIR\tools\engines\whisper\ggml-cpu.dll"
  Delete "$INSTDIR\tools\engines\whisper\ggml.dll"
  Delete "$INSTDIR\tools\engines\whisper\msvcp140.dll"
  Delete "$INSTDIR\tools\engines\whisper\vcomp140.dll"
  Delete "$INSTDIR\tools\engines\whisper\vcruntime140.dll"
  Delete "$INSTDIR\tools\engines\whisper\vcruntime140_1.dll"
  Delete "$INSTDIR\tools\engines\whisper\whisper-cli.exe"
  Delete "$INSTDIR\tools\engines\whisper\whisper.dll"
  Delete "$INSTDIR\vcomp140.dll"
  Delete "$INSTDIR\vcruntime140.dll"
  Delete "$INSTDIR\vcruntime140_1.dll"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src\third_party\rust"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src\third_party"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-container-adapter\vendor\libavif"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3\tests"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35\src"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-container-adapter\vendor"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libwebp-sys-0.9.6\vendor"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pxfm-0.1.30"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zlib-rs-0.6.7"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\webp-0.3.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-future-0.2.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\aligned-vec-0.6.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\av1-grain-0.2.5"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\y4m-0.8.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\half-2.7.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_core-1.0.229"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quote-1.0.47"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\jobserver-0.1.35"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\heck-0.5.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\arrayvec-0.7.8"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zmij-1.0.23"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cfg-if-1.0.5"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\lock_api-0.4.14"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\noop_proc_macro-0.3.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rav1e-0.8.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-2.0.20"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\new_debug_unreachable-1.0.6"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\av-scenechange-0.14.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\either-1.18.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\scopeguard-1.2.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-rational-0.4.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitstream-io-4.10.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\imgref-1.12.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\stable_deref_trait-1.2.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\once_cell-1.21.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crc32fast-1.5.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\adler2-2.0.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\sources"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\to_method-1.1.0"
  RMDir "$INSTDIR\tools\engines\upscale-lite\models"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.8.57"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-3.0.6"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\flate2-1.1.10"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rgb-0.8.53"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot-0.12.5"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libc-0.2.189"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\raw-cpuid-11.6.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itertools-0.14.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-numerics-0.2.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\anyhow-1.0.104"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\unicode-ident-1.0.26"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-0.2.128"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-deque-0.8.8"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_json-1.0.151"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\fax-0.2.7"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.1.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\getrandom-0.4.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\smallvec-1.16.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\cc-1.4.7"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\paste-1.0.15"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\byteorder-lite-0.1.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-strings-0.4.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\ravif-0.13.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\fdeflate-0.3.7"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\v_frame-0.3.9"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\log-0.4.34"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-macro-support-0.2.128"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\simd_helpers-0.1.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.9.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\proc-macro2-1.0.107"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\strum_macros-0.26.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-0.25.10"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\strum-0.26.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-jpeg-0.5.15"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-traits-0.2.19"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rav1d-1.1.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bytemuck-1.25.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-container-adapter"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-1.0.18"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\avif-serialize-0.8.9"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\moxcms-0.8.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-epoch-0.9.21"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\libwebp-sys-0.9.6"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\thiserror-impl-2.0.20"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\miniz_oxide-0.8.9"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-0.4.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\weezl-0.1.12"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.8.57"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zune-core-0.5.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\gif-0.14.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde_derive-1.0.229"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\simd-adler32-0.3.10"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-1.12.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-result-0.3.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\pastey-0.1.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\itoa-1.0.18"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\find-msvc-tools-0.1.13"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\png-0.18.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\serde-1.0.229"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\color_quant-1.1.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bumpalo-3.20.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\arg_enum_proc_macro-0.3.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-0.2.128"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\byteorder-1.5.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\wasm-bindgen-shared-0.2.128"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\glob-0.3.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-derive-0.4.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\parking_lot_core-0.9.12"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-implement-0.60.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\autocfg-1.5.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-threading-0.1.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\assert_matches-1.5.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-derive-0.7.35"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\memchr-2.8.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-0.61.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-core-0.61.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\bitflags-2.13.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-bigint-0.4.8"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-interface-0.59.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\as-slice-0.2.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\profiling-procmacros-1.0.18"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\built-0.8.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\zerocopy-0.7.35"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\maybe-rayon-0.1.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\crossbeam-utils-0.8.23"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\nom-8.0.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\atomig-macro-0.4.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\aligned-0.4.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\nasm-rs-0.3.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\num-integer-0.1.47"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\tiff-0.11.3"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\shlex-2.0.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\equator-0.4.2"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\syn-2.0.119"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\quick-error-2.0.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-link-0.2.1"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\loop9-0.1.5"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\windows-collections-0.2.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rustversion-1.0.23"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\image-webp-0.2.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\no_std_io2-0.9.4"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\rayon-core-1.13.0"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03\equator-macro-0.4.2"
  RMDir "$INSTDIR\tools\engines\whisper"
  RMDir "$INSTDIR\tools\engines\upscale-lite"
  RMDir "$INSTDIR\licenses\project-dependencies\upscale-lite"
  RMDir "$INSTDIR\licenses\project-dependencies\image-codecs-g03"
  RMDir "$INSTDIR\tools\engines\aria2"
  RMDir "$INSTDIR\tools\engines\ffmpeg"
  RMDir "$INSTDIR\tools\engines\yt-dlp"
  RMDir "$INSTDIR\licenses\yt-dlp"
  RMDir "$INSTDIR\tools\archpr"
  RMDir "$INSTDIR\licenses\ffmpeg"
  RMDir "$INSTDIR\models\ocr-v3"
  RMDir "$INSTDIR\licenses\project-dependencies"
  RMDir "$INSTDIR\tools\engines"
  RMDir "$INSTDIR\models"
  RMDir "$INSTDIR\licenses"
  RMDir "$INSTDIR\tools"
  Delete "$INSTDIR\Uninstall FurinaKit.exe"
  RMDir "$INSTDIR"

  Delete "$DESKTOP\FurinaKit.lnk"
  Delete "$SMPROGRAMS\FurinaKit\FurinaKit.lnk"
  RMDir "$SMPROGRAMS\FurinaKit"

  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\furinakit"
SectionEnd
