use furinakit_image_codecs::{colour::{self,Encoding},decode,image_basic};
use image::{DynamicImage,ImageBuffer,Rgba};
use std::{path::{Path,PathBuf},sync::atomic::{AtomicUsize,Ordering}};
static SEQ:AtomicUsize=AtomicUsize::new(0);
struct Temp(PathBuf);
impl Temp{fn new()->Self{let root=PathBuf::from(std::env::var_os("FURINAKIT_IMAGE_TEST_ROOT").expect("Explicit development test directory required"));std::fs::create_dir_all(&root).unwrap();let p=root.join(format!("{}-{}",std::process::id(),SEQ.fetch_add(1,Ordering::Relaxed)));std::fs::create_dir(&p).unwrap();Self(p)}}
impl Drop for Temp{fn drop(&mut self){let _=std::fs::remove_dir_all(&self.0);}}
fn source()->DynamicImage{DynamicImage::ImageRgba8(ImageBuffer::from_fn(96,64,|x,y|Rgba([(x*19+y*7)as u8,(x*3+y*23)as u8,(x*x+y*11)as u8,((x+y)*3)as u8])))}
fn fixture(n:&str)->Vec<u8>{std::fs::read(PathBuf::from(std::env::var_os("FURINAKIT_AVIF_FIXTURES").unwrap()).join(n)).unwrap()}
fn encode(path:&Path,output:&Path,format:&str,quality:u8)->serde_json::Value{image_basic::encode("image-format-convert",&serde_json::json!({"format":format,"quality":quality}),path,output,format,&||Ok(())).unwrap()}
#[test]fn defaults_and_quality_contract(){assert_eq!(image_basic::extension("image-format-convert",&serde_json::json!({})).unwrap(),"webp");assert_eq!(image_basic::extension("image-format-convert",&serde_json::json!({"format":"jpeg"})).unwrap(),"jpg");assert!(image_basic::extension("image-format-convert",&serde_json::json!({"format":"exe"})).is_err());}
#[test]fn srgb_noop_and_alpha_exact(){let input=source();let expected=input.to_rgba8();let result=colour::to_srgb(input,&Encoding{primaries:1,transfer:13,..Default::default()},&||Ok(()),&mut Vec::new()).unwrap();assert_eq!(result.to_rgba8(),expected);}
#[test]fn icc_has_priority_over_conflicting_hdr_cicp(){let input=source();let original=input.to_rgba8();let mut notes=Vec::new();let result=colour::to_srgb(input,&Encoding{icc:moxcms::ColorProfile::new_srgb().encode().unwrap(),primaries:9,transfer:16,max_cll:1000},&||Ok(()),&mut notes).unwrap().to_rgba8();assert!(!notes.iter().any(|n|n.starts_with("HDR")));for(a,b)in result.pixels().zip(original.pixels()){assert_eq!(a[3],b[3]);for c in 0..3{assert!(a[c].abs_diff(b[c])<=1);}}}
#[test]fn malformed_icc_and_reserved_cicp_fail_not_assume(){assert!(colour::to_srgb(source(),&Encoding{icc:vec![1;132],primaries:1,transfer:13,max_cll:0},&||Ok(()),&mut Vec::new()).is_err());assert!(colour::to_srgb(source(),&Encoding{primaries:3,transfer:13,..Default::default()},&||Ok(()),&mut Vec::new()).is_err());}
#[test]fn wide_gamut_changes_rgb_preserves_alpha(){let img=DynamicImage::ImageRgba16(ImageBuffer::from_pixel(2,1,image::Rgba([42000u16,23000,16000,23456])));let result=colour::to_srgb(img,&Encoding{primaries:12,transfer:13,..Default::default()},&||Ok(()),&mut Vec::new()).unwrap().into_rgba16();let p=result.get_pixel(0,0);assert_eq!(p[3],23456);assert!(p[0]>42000);assert!(p[1]<23000);}
#[test]fn hdr_tone_mapping_is_explicit_and_monotonic(){for tc in [16u16,18]{let img=DynamicImage::ImageRgba16(ImageBuffer::from_fn(256,1,|x,_|image::Rgba([x as u16*257,x as u16*257,x as u16*257,49151])));let mut notes=Vec::new();let result=colour::to_srgb(img,&Encoding{primaries:9,transfer:tc,max_cll:1000,..Default::default()},&||Ok(()),&mut notes).unwrap().into_rgba16();assert!(notes.iter().any(|n|n.starts_with("HDR")));assert!(result.pixels().all(|p|p[3]==49151));let values:Vec<_>=result.pixels().map(|p|p[1]).collect();assert!(values.windows(2).all(|p|p[0]<=p[1]));assert!(values[0]<3&&values[255]>65000);}}
#[test]fn avif_container_orientation_gain_map_and_icc_policy(){for name in ["abc_color_irot_alpha_irot.avif","paris_icc_exif_xmp.avif","colors_hdr_rec2020.avif","seine_sdr_gainmap_srgb.avif"]{let image=decode::decode(&fixture(name),&||Ok(())).unwrap();if name.starts_with("abc"){assert_eq!((image.image.width(),image.image.height()),(256,512));}if name.contains("gainmap"){assert!(image.notes.iter().any(|n|n.contains("gain map")));}if name.contains("hdr_rec"){assert!(image.notes.iter().any(|n|n.starts_with("HDR")));}}}
#[test]fn real_lossy_webp_quality_and_alpha(){let tmp=Temp::new();let input=tmp.0.join("input.png");let src=source();src.save(&input).unwrap();let mut outputs=Vec::new();for q in [15u8,92]{let output=tmp.0.join(format!("q{q}.webp"));let info=encode(&input,&output,"webp",q);assert_eq!(info["qualityApplied"],true);assert_eq!(info["losslessEncoding"],false);let b=std::fs::read(&output).unwrap();assert_eq!(&b[..4],b"RIFF");let mut p=12;let mut lossy=false;while p+8<=b.len(){let n=u32::from_le_bytes(b[p+4..p+8].try_into().unwrap())as usize;if &b[p..p+4]==b"VP8 "{lossy=true;}assert_ne!(&b[p..p+4],b"VP8L");p+=8+n+(n&1);}assert!(lossy);let decoded=image::open(&output).unwrap().to_rgba8();for(a,b)in src.to_rgba8().pixels().zip(decoded.pixels()){assert_eq!(a[3],b[3]);}outputs.push(b);}assert_ne!(outputs[0],outputs[1]);assert!(outputs[1].len()>outputs[0].len());}
#[test]fn avif_real_encoding_quality_roundtrip(){let tmp=Temp::new();let input=tmp.0.join("input.png");source().save(&input).unwrap();let mut files=Vec::new();for q in [20u8,90]{let out=tmp.0.join(format!("q{q}.avif"));let info=encode(&input,&out,"avif",q);assert_eq!(info["qualityApplied"],true);let data=std::fs::read(&out).unwrap();assert!(furinakit_avif_decoder::is_avif(&data));let decoded=decode::decode(&data,&||Ok(())).unwrap();assert_eq!((decoded.image.width(),decoded.image.height()),(96,64));files.push(data);}assert_ne!(files[0],files[1]);assert!(files[1].len()>files[0].len());}
#[test]fn seven_converter_outputs_and_no_overwrite(){let tmp=Temp::new();let input=tmp.0.join("in.png");source().save(&input).unwrap();for ext in ["png","jpg","bmp","tiff","gif","webp","avif"]{let out=tmp.0.join(format!("result.{ext}"));encode(&input,&out,ext,75);let decoded=decode::load(&out,&||Ok(())).unwrap();assert_eq!((decoded.image.width(),decoded.image.height()),(96,64));assert!(image_basic::encode("image-format-convert",&serde_json::json!({"format":ext}),&input,&out,ext,&||Ok(())).is_err());}}
#[test]fn high_bit_depth_png_and_cancellation(){let tmp=Temp::new();let input=tmp.0.join("in.png");let source=DynamicImage::ImageRgba16(ImageBuffer::from_fn(20,10,|x,y|image::Rgba([(x*3011)as u16,(y*6011)as u16,22222u16,49151u16])));source.save(&input).unwrap();let out=tmp.0.join("out.png");encode(&input,&out,"png",90);let decoded=image::open(&out).unwrap();assert_eq!(decoded.color(),image::ColorType::Rgba16);assert!(decode::load(&input,&||Err("cancelled".into())).is_err());}
#[test]fn png_gamma_and_cicp_narrow_range(){
 let mut bytes=Vec::new();{
  let mut encoder=png::Encoder::new(&mut bytes,1,1);encoder.set_color(png::ColorType::Rgba);encoder.set_depth(png::BitDepth::Eight);encoder.set_source_gamma(png::ScaledFloat::new(1.0));let mut w=encoder.write_header().unwrap();w.write_image_data(&[128,128,128,127]).unwrap();
 }
 let decoded=decode::decode(&bytes,&||Ok(())).unwrap();let p=*decoded.image.to_rgba8().get_pixel(0,0);println!("PNG gamma pixel={p:?} notes={:?}",decoded.notes);assert!((187..=189).contains(&p[0]));assert_eq!(p[3],127);
 let mut info=png::Info::with_size(1,1);info.color_type=png::ColorType::Rgba;info.bit_depth=png::BitDepth::Eight;info.coding_independent_code_points=Some(png::CodingIndependentCodePoints{color_primaries:1,transfer_function:13,matrix_coefficients:0,is_video_full_range_image:false});
 let mut bytes=Vec::new();{let encoder=png::Encoder::with_info(&mut bytes,info).unwrap();let mut w=encoder.write_header().unwrap();w.write_chunk(png::chunk::cICP,&[1,13,0,0]).unwrap();w.write_image_data(&[16,235,16,127]).unwrap();}
 let decoded=decode::decode(&bytes,&||Ok(())).unwrap();assert_eq!(decoded.image.to_rgba8().get_pixel(0,0).0,[0,255,0,127]);
}
#[test]fn hlg_luminance_ootf_preserves_scene_chroma_and_alpha(){
 let codes=[49151u16,16384,6554,23456];let input=DynamicImage::ImageRgba16(ImageBuffer::from_pixel(1,1,Rgba(codes)));
 let out=colour::to_srgb(input,&Encoding{primaries:1,transfer:18,max_cll:1000,..Default::default()},&||Ok(()),&mut Vec::new()).unwrap().into_rgba16();let p=out.get_pixel(0,0);assert_eq!(p[3],23456);
 // Independent scalar BT.2100 + extended-Reinhard reference, 709 primaries.
 let scene=codes[..3].iter().map(|&n|{let e=f64::from(n)/65535.0;if e<=0.5{e*e/3.0}else{(((e-0.55991073)/0.17883277).exp()+0.28466892)/12.0}}).collect::<Vec<_>>();
 let ys=0.2126*scene[0]+0.7152*scene[1]+0.0722*scene[2];let gain=ys.powf(0.2)*1000.0/203.0;let y=ys*gain;let white=1000.0f64/203.0;let k=(1.0+y/(white*white))/(1.0+y);
 for c in 0..3{let l=(scene[c]*gain*k).clamp(0.0,1.0);let expected=(if l<=0.0031308{12.92*l}else{1.055*l.powf(1.0/2.4)-0.055})*65535.0;assert!((f64::from(p[c])-expected).abs()<12.0,"channel {c}: {} expected {expected}",p[c]);}
}
#[test]fn ico_multiple_real_layers_and_cancelled_artifacts(){
 use furinakit_image_codecs::image_artifacts;
 let t=Temp::new();let input=t.0.join("in.png");source().save(&input).unwrap();let out=t.0.join("out.ico");
 let info=image_basic::encode("image-to-ico",&serde_json::json!({"sizes":[16,32,64]}),&input,&out,"ico",&||Ok(())).unwrap();assert_eq!(info["sizes"],serde_json::json!([16,32,64]));let bytes=std::fs::read(&out).unwrap();assert_eq!(&bytes[..6],&[0,0,1,0,3,0]);
 for (i,size) in [16u32,32,64].iter().enumerate(){let a=6+i*16;let len=u32::from_le_bytes(bytes[a+8..a+12].try_into().unwrap())as usize;let off=u32::from_le_bytes(bytes[a+12..a+16].try_into().unwrap())as usize;let layer=image::load_from_memory(&bytes[off..off+len]).unwrap();assert_eq!(layer.width(),*size);assert_eq!(layer.height(),*size);assert!(layer.to_rgba8().pixels().any(|p|p[3]<255));}
 let copy=t.0.join("copy.png");assert!(image_artifacts::copy_new(&input,&copy,128000000,&||Err("cancel".into())).is_err());assert!(!copy.exists());
 std::fs::write(&copy,b"protected").unwrap();assert!(image_artifacts::copy_new(&input,&copy,128000000,&||Ok(())).is_err());assert_eq!(std::fs::read(&copy).unwrap(),b"protected");
 let zip=t.0.join("bad.zip");assert!(image_artifacts::zip(&[("../bad.png".into(),input.clone())],&zip,&||Ok(())).is_err());assert!(!zip.exists());
 let scratch=image_artifacts::Scratch::create(&t.0,"owned").unwrap();let path=scratch.0.clone();assert!(image_artifacts::Scratch::create(&t.0,"owned").is_err());drop(scratch);assert!(!path.exists());
}
#[test]fn animated_gif_crop_retains_delays_repeat_and_disposal(){
 use std::borrow::Cow;let t=Temp::new();let input=t.0.join("in.gif");let mut bytes=Vec::new();{
 let mut encoder=gif::Encoder::new(&mut bytes,8,8,&[0,0,0,255,0,0,0,255,0,0,0,255]).unwrap();encoder.set_repeat(gif::Repeat::Infinite).unwrap();
 for (i,delay)in [7u16,23,41].iter().enumerate(){let mut f=gif::Frame::default();f.width=8;f.height=8;f.delay=*delay;f.dispose=gif::DisposalMethod::Background;f.transparent=Some(0);f.buffer=Cow::Owned((0..64).map(|n|if n%5==0{0}else{(i+1)as u8}).collect());encoder.write_frame(&f).unwrap();}}
 std::fs::write(&input,&bytes).unwrap();let out=t.0.join("crop.gif");let info=furinakit_image_codecs::image_gif::encode("gif-crop",&serde_json::json!({"x":2,"y":2,"width":4,"height":4}),&input,&out,&||Ok(())).unwrap();assert_eq!(info["durationMs"],710);assert_eq!(info["frames"],3);
 let output=std::fs::read(&out).unwrap();assert!(output.windows(11).any(|w|w==b"NETSCAPE2.0"));let mut opt=gif::DecodeOptions::new();opt.set_color_output(gif::ColorOutput::Indexed);let mut dec=opt.read_info(std::io::Cursor::new(output)).unwrap();assert_eq!((dec.width(),dec.height()),(4,4));
 for (i,delay)in [7u16,23,41].iter().enumerate(){let f=dec.read_next_frame().unwrap().unwrap();assert_eq!(f.delay,*delay);assert_eq!(f.dispose,gif::DisposalMethod::Background);assert_eq!(f.transparent,Some(0));let expected:Vec<u8>=(2..6).flat_map(|y|(2..6).map(move|x|if (y*8+x)%5==0{0}else{(i+1)as u8})).collect();assert_eq!(&*f.buffer,&expected);}
 assert!(dec.read_next_frame().unwrap().is_none());assert_eq!(std::fs::read(&input).unwrap(),bytes);
}
