#![cfg(windows)]
use std::{path::PathBuf,sync::atomic::{AtomicUsize,AtomicBool,Ordering},time::{Duration,Instant}};
use furinakit_image_codecs::image_process::{execute,execute_with_limits};
static SEQ:AtomicUsize=AtomicUsize::new(0);
struct Temp(PathBuf);impl Temp{fn new()->Self{let base=PathBuf::from(std::env::var_os("FURINAKIT_IMAGE_TEST_ROOT").unwrap());std::fs::create_dir_all(&base).unwrap();let p=base.join(format!("proc-{}-{}",std::process::id(),SEQ.fetch_add(1,Ordering::Relaxed)));std::fs::create_dir(&p).unwrap();Self(p)}}impl Drop for Temp{fn drop(&mut self){let _=std::fs::remove_dir_all(&self.0);}}
fn worker()->PathBuf{PathBuf::from(env!("CARGO_BIN_EXE_furinakit-image-worker"))}
fn request(t:&Temp,format:&str,size:u32)->serde_json::Value{let input=t.0.join("input.png");let image=image::RgbaImage::from_fn(size,size,|x,y|image::Rgba([(x*13+y*37)as u8,(x^y)as u8,((x*y)%251)as u8,255]));image.save(&input).unwrap();serde_json::json!({"protocol":1,"tool":"image-format-convert","args":{"format":format,"quality":90},"input":input,"output":t.0.join(format!("output.{format}"))})}
#[test]fn isolated_real_encoding(){let t=Temp::new();let r=request(&t,"webp",96);let result=execute(&worker(),&r,&||Ok(())).unwrap();assert_eq!(result["isolatedWorker"],true);assert!(result["workerPeakMemoryBytes"].as_u64().unwrap()>0);assert!(result["workerPeakMemoryBytes"].as_u64().unwrap()<1024*1024*1024);assert_eq!(result["qualityApplied"],true);assert_eq!(image::open(t.0.join("output.webp")).unwrap().width(),96);println!("PEAK_COMMITTED_BYTES {}",result["workerPeakMemoryBytes"]);}
#[test]fn active_cancel_kills_worker_and_next_request_succeeds(){let t=Temp::new();let request=request(&t,"avif",1024);let cancelled=AtomicBool::new(false);let start=Instant::now();std::thread::scope(|s|{s.spawn(||{std::thread::sleep(Duration::from_millis(80));cancelled.store(true,Ordering::SeqCst);});let result=execute(&worker(),&request,&||if cancelled.load(Ordering::SeqCst){Err("TEST_CANCEL".into())}else{Ok(())});assert!(result.unwrap_err().contains("TEST_CANCEL"));});assert!(start.elapsed()<Duration::from_secs(3));let again=Temp::new();let small=super_request(&again);assert!(execute(&worker(),&small,&||Ok(())).is_ok());}
fn super_request(t:&Temp)->serde_json::Value{request(t,"png",16)}
#[test]fn timeout_is_enforced_and_missing_component_is_clear(){let t=Temp::new();let r=request(&t,"avif",1024);let start=Instant::now();let e=execute_with_limits(&worker(),&r,&||Ok(()),512*1024*1024,Duration::from_millis(30)).unwrap_err();assert!(e.contains("timed out"));assert!(start.elapsed()<Duration::from_secs(3));assert!(execute(&t.0.join("missing.exe"),&r,&||Ok(())).unwrap_err().contains("missing"));}
#[test]fn malformed_worker_request_and_no_overwrite(){let t=Temp::new();let mut r=request(&t,"png",16);r["protocol"]=serde_json::json!(99);assert!(execute(&worker(),&r,&||Ok(())).unwrap_err().contains("protocol"));r["protocol"]=serde_json::json!(1);let out=t.0.join("output.png");std::fs::write(&out,b"protected").unwrap();assert!(execute(&worker(),&r,&||Ok(())).is_err());assert_eq!(std::fs::read(&out).unwrap(),b"protected");}
